import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Was zeigt dieses Labor für feste Zeitschritte?', answer: 'Es führt dasselbe bewegte Objekt durch eine Schleife mit variablem Delta und durch einen Akkumulator mit festem Zeitschritt. Wiederholbare Frame-Spitzen machen Simulationszeit, Positionsdrift und Nachholschritte sichtbar, ohne eine Game-Engine auszuführen.' },
  { question: 'Was ist der Unterschied zwischen variablem und festem Delta?', answer: 'Das variable Modell aktualisiert einmal pro gerendertem Frame und verwendet dessen Dauer. Das feste Modell arbeitet in gleich großen Simulationsschritten und verarbeitet per Akkumulator so viele Schritte, wie die vergangene Echtzeit verlangt. Dadurch hängt das feste Modell weniger von der Bildrate ab, kann nach einem langen Frame aber zusätzliche Arbeit benötigen.' },
  { question: 'Was bedeutet die Eingabe für eine Frame-Spitze?', answer: 'Sie addiert zusätzliche Millisekunden zu jedem ausgewählten Spitzen-Frame. Mit dem Abstand legst du fest, wie oft die Spitze erscheint. So entsteht ein wiederholbares Stottermuster statt einer zufälligen Messung.' },
  { question: 'Was ändert die Delta-Begrenzung?', answer: 'Die Begrenzung beschränkt die Dauer, die das variable Modell bei einem langen Frame verwendet. Das kann einen zu großen Sprung verhindern, lässt diese Simulationsuhr aber hinter der Echtzeit zurückfallen. Der feste Akkumulator berücksichtigt weiterhin die gesamte Frame-Dauer.' },
  { question: 'Ist dies ein Profiler oder ein Ersatz für Spieltests?', answer: 'Nein. Es ist ein deterministisches Lehr- und Designlabor mit vorgegebenen Zahlen. Es misst kein Gerät, diagnostiziert keine Engine, modelliert keine Renderkosten und beweist nicht, dass eine Schleife für jedes Spiel richtig ist.' },
];

const howTo = [
  { name: 'Den Frame-Rhythmus wählen', text: 'Lege eine Zielbildrate fest und füge eine wiederholbare Spitze in Millisekunden hinzu. Mit dem Abstand bestimmst du, in welchem Frame sie erscheint.' },
  { name: 'Den Simulationsschritt festlegen', text: 'Wähle die Dauer des festen Zeitschritts. Ein Wert nahe 16,667 Millisekunden entspricht ungefähr 60 Simulationsupdates pro Sekunde.' },
  { name: 'Beiden Welten dieselbe Bewegung geben', text: 'Setze Geschwindigkeit und Laufzeit. Beide Modelle bewegen dasselbe Objekt, daher entsteht der Positionsunterschied durch den Umgang mit der verstrichenen Zeit.' },
  { name: 'Eine Begrenzung bewusst testen', text: 'Aktiviere die Delta-Begrenzung und vergleiche die Simulationszeit des variablen Modells mit dem festen Akkumulator. Eine Begrenzung ist eine Entscheidung mit Kosten, keine kostenlose Korrektur.' },
  { name: 'Die Hinweise lesen', text: 'Prüfe die beiden Spuren, die Drift-Zusammenfassung, die Zeitleiste, das Nachholverhalten und die zugängliche Frame-Tabelle. Ändere beim Erklären oder Debuggen jeweils nur eine Eingabe.' },
];

const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Labor für Game Delta-Zeit und feste Zeitschritte', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Variable Delta-Zeit mit einem festen Zeitschritt vergleichen', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'delta-zeit-und-fester-timestep-spielelabor',
  title: 'Game Delta Zeit und festes Zeitschritt Labor',
  description: 'Vergleiche variable und feste Game-Loops mit wiederholbaren Frame-Spitzen, Bewegung, Nachholschritten und sichtbarer Zeitdrift.',
  ui: {
    controlsTitle: 'Frame-Muster erstellen', fpsLabel: 'Zielbildrate', fpsHint: 'Gerenderte Frames pro Sekunde', spikeLabel: 'Frame-Spitze', spikeHint: 'Zusätzliche Zeit für Spitzen-Frames', spikeEveryLabel: 'Spitze alle Frames', fixedDtLabel: 'Fester Zeitschritt', fixedDtHint: 'Gleich große Simulationsschritte', velocityLabel: 'Objektgeschwindigkeit', durationLabel: 'Laufzeit', clampLabel: 'Delta-Obergrenze', clampToggle: 'Variables Delta begrenzen', runLabel: 'Experiment starten', resetLabel: 'Werte zurücksetzen', stageKicker: 'Das Versuchsfeld', stageTitle: 'Zwei Uhren, ein bewegtes Objekt', stageCaption: 'Balken zeigen die Ruckler, Linien verfolgen beide Positionen und die untere Spur isoliert die Drift, die Endwerte verbergen können.', frameTraceLabel: 'Frame-Dauern', positionPlotLabel: 'Objektposition', differencePlotLabel: 'Positionsunterschied zum festen Pfad', variableLane: 'Variables Delta', fixedLane: 'Fester Akkumulator', frameCountLabel: 'Gerenderte Frames', wallTimeLabel: 'Echtzeit', variableTimeLabel: 'Variable Simulationszeit', fixedTimeLabel: 'Feste Simulationszeit', divergenceLabel: 'Positionsunterschied', stepsLabel: 'Feste Simulationsschritte', diagnosticsTitle: 'Frame-Lesung', stableStatus: 'Die beiden Pfade bleiben bei diesem Muster ausgerichtet.', variableStatus: 'Der variable Pfad läuft voraus, weil seine Frame-Dauern die Spitzen enthalten.', fixedStatus: 'Der feste Pfad holt nach einem langen Frame mit mehreren Simulationsschritten auf.', clampStatus: 'Die Begrenzung verkleinert den Sprung des variablen Pfads und lässt ihn hinter der verstrichenen Echtzeit zurück.', timelineTitle: 'Das Bewegungsprotokoll', timelineCaption: 'Position über der verstrichenen Echtzeit. Eine gestrichelte Linie markiert gleiche feste Schritte.', frameAxis: 'Verstrichene Echtzeit', positionAxis: 'Objektposition', legendVariable: 'Variabler Delta-Pfad', legendFixed: 'Pfad mit festem Zeitschritt', legendSpike: 'Frame-Spitze', tableTitle: 'Zugängliches Frame-Protokoll', tableFrame: 'Frame', tableWall: 'Echtzeit', tableVariable: 'Variable Position', tableFixed: 'Feste Position', tableDelta: 'Unterschied', modelNote: 'Das variable Modell verwendet die aktuelle Frame-Dauer einmal mit der Geschwindigkeit. Das feste Modell sammelt die gesamte Echtzeit und bewegt sich in gleichen Schritten. Kein Pfad ist eine Leistungsmessung.', privacyDisclosure: 'Deine Werte werden nur in diesem Browser gespeichert, damit das Experiment bei der Rückkehr bereitsteht. Es werden keine Spieldaten oder Telemetrie gesendet.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'Einheiten', statusReady: 'Experiment aktualisiert',
  },
  seo: [
    { type: 'title', level: 2, text: 'Die Uhr im Game-Loop verstehen' },
    { type: 'paragraph', html: 'Jeder gerenderte Frame liefert dem Spiel eine neue verstrichene Zeit. In einer Schleife mit variablem Delta wird Bewegung oft als <code>position += velocity × frameTime</code> aktualisiert. Bei gleichmäßigen Frames bleibt die Durchschnittsgeschwindigkeit passend, aber ein einzelnes Update wird so groß wie der Frame, der es ausgelöst hat. Ein Hitch ist deshalb nicht nur eine kurze Bildpause: Er verändert die Spielzeit dieses Updates.' },
    { type: 'title', level: 2, text: 'Variable Integration mit einem festen Akkumulator vergleichen' },
    { type: 'paragraph', html: 'Eine Schleife mit festem Zeitschritt addiert jede Frame-Dauer zu einem Akkumulator und verbraucht dann wiederholt einen gewählten Schritt wie <code>16,667 ms</code>. Die Simulation sieht gleich große Updates, während der Renderer in einem anderen Rhythmus arbeiten darf. Der Rest bleibt im Akkumulator für den nächsten Frame. Bei einem langen Frame führt die feste Schleife mehrere kleine Updates aus, um die verstrichene Zeit abzubilden. Die Schrittgröße bleibt stabil, aber es kann ein Nachholstoß entstehen.' },
    { type: 'table', headers: ['Situation', 'Variabler Delta-Pfad', 'Pfad mit festem Zeitschritt', 'Zu treffende Entscheidung'], rows: [['Gleichmäßiges Rendering', 'Ein Update verwendet jede normale Frame-Dauer', 'Gleiche Schritte verbrauchen die angesammelte Zeit', 'Beide Pfade sollten der Bewegung eng folgen.'], ['Langer Frame', 'Ein großes Update kann ein Objekt zu weit bewegen', 'Mehrere feste Updates holen die Echtzeit ein', 'Drift und Nachholzahl gemeinsam prüfen.'], ['Andere Bildrate', 'Die Updategröße ändert sich mit der Bildrate', 'Der Simulationsschritt bleibt gleich', 'Feste Schritte verringern die Abhängigkeit vom Rendering.'], ['Delta-Obergrenze', 'Zeit über der Grenze wird ignoriert', 'Der Akkumulator erhält weiterhin die volle Frame-Dauer', 'Nur begrenzen, wenn verlorene Zeit akzeptabel ist.']] },
    { type: 'title', level: 2, text: 'Erkennen, was eine Frame-Spitze bewirkt' },
    { type: 'paragraph', html: 'Bei 60 Frames pro Sekunde dauert ein regelmäßiger Frame etwa <code>16,667 ms</code>. Mit einer zusätzlichen Spitze von <code>80 ms</code> wird ein Frame ungefähr <code>96,667 ms</code> lang. Das variable Modell verarbeitet diese Dauer in einem einzigen Update. Das feste Modell verarbeitet stattdessen ungefähr sechs Schritte zu je <code>16,667 ms</code>. Die gesamte verstrichene Zeit kann gleich sein, während der Weg durch die Simulation anders verläuft.' },
    { type: 'title', level: 2, text: 'Positionsdrift und Nachholen gemeinsam lesen' },
    { type: 'paragraph', html: 'Der Positionsunterschied ist der variable Pfad minus der feste Pfad. Er zeigt, wie weit sich die beiden Integrationsregeln trennen, nicht automatisch, welche Regel richtig ist. Die Nachholzahl zeigt, wie viel feste Arbeit in einem gerenderten Frame nötig war. Ein großer Unterschied deutet auf sichtbare Bewegungsabweichung hin; eine große Nachholzahl deutet auf ein mögliches CPU-Budgetproblem hin. Beides hängt zusammen, ist aber nicht dieselbe Diagnose.' },
    { type: 'title', level: 2, text: 'Delta-Begrenzung als Richtlinie behandeln' },
    { type: 'paragraph', html: 'Eine Begrenzung kann verhindern, dass ein pausierter Tab, ein Breakpoint oder ein starker Hitch eine Figur teleportiert oder einen Physikkörper durch Geometrie schickt. Der Preis ist, dass die variable Uhr hinter der echten verstrichenen Zeit zurückbleibt. Wenn das Spiel Zeit bewahren muss, eignet sich ein fester Akkumulator oder eine andere Wiederherstellungsregel. Wenn das Spiel Sprünge begrenzen und reaktionsfähig bleiben muss, kann ein Clamp passen, aber die verlorene Zeit muss beabsichtigt sein.' },
    { type: 'title', level: 2, text: 'Die Schleife nach der Aufgabe wählen' },
    { type: 'table', headers: ['Aufgabe im Game-Loop', 'Sinnvoller Standard', 'Grund'], rows: [['Physik, Kollisionen oder deterministisches Gameplay', 'Fester Zeitschritt', 'Gleiche Schritte machen die Simulation weniger abhängig vom Render-Rhythmus.'], ['Einfache visuelle Bewegung ohne Zustandsaufbau', 'Variables Delta', 'Das Update ist klein und braucht meist keine Nachholwarteschlange.'], ['Gameplay-Simulation mit glatter Darstellung', 'Fester Update-Schritt mit Interpolation', 'Die Simulation behält ihren Schritt, während die Darstellung Zwischenbewegung verbirgt.'], ['Erholung nach einem schweren Stillstand', 'Begrenzte Nachholregel', 'Ein schlechter Frame soll keine unbegrenzte Simulationsarbeit erzeugen.']] },
    { type: 'title', level: 2, text: 'Einen wiederholbaren Tuning-Ablauf nutzen' },
    { type: 'paragraph', html: 'Beginne ohne Spitzen und prüfe, ob beide Pfade übereinstimmen. Füge einen wiederholbaren Hitch hinzu und ändere danach seinen Abstand, um zu sehen, ob der sichtbare Fehler anwächst oder sich beruhigt. Passe den festen Schritt an und beobachte die Nachholzahl, bevor du die Geschwindigkeit änderst. Aktiviere zuletzt die Begrenzung und vergleiche die variable Simulationszeit mit der Echtzeit. So trennst du die Ursache einer Abweichung von der Regel, die sie begrenzen soll.' },
    { type: 'tip', title: 'Was dieses Experiment nicht beweisen kann', html: 'Das Labor verwendet festgelegte Frame-Dauern und eine konstante Geschwindigkeit. Es erklärt daher Timing-Verhalten, misst aber kein Gerät und bestätigt keine Engine. Echte Physik, Eingabeabtastung, Netzwerk, Interpolation und ein begrenztes Frame-Budget können die beste Lösung verändern. Nutze das Ergebnis als Hypothese und überprüfe sie im tatsächlichen Spiel.' },
  ],
  faq,
  bibliographyTitle: 'Referenzen zu Game-Loops',
  bibliography: bibliographyEntries,
  howTo,
  schemas: [softwareApplication, faqPage, howToSchema],
};
