import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: '¿Qué demuestra este laboratorio de timestep fijo?', answer: 'Ejecuta el mismo objeto en movimiento con un bucle de delta variable y con un acumulador de timestep fijo. Los picos de frame hacen visible la diferencia para inspeccionar tiempo simulado, deriva de posición y pasos de recuperación sin ejecutar un motor de juego.' },
  { question: '¿Cuál es la diferencia entre delta variable y timestep fijo?', answer: 'El modelo variable avanza una vez por frame renderizado usando su duración. El modelo fijo avanza en pasos de simulación iguales y usa un acumulador para procesar los pasos que exige el tiempo real transcurrido. Los pasos fijos reducen la dependencia de la tasa de renderizado, aunque un frame largo puede exigir trabajo adicional.' },
  { question: '¿Qué representa la entrada de pico de frame?', answer: 'Añade milisegundos extra a cada frame marcado como pico. El campo de frecuencia decide cada cuántos frames aparece, para crear un patrón de hitch repetible en lugar de depender de una traza de rendimiento aleatoria.' },
  { question: '¿Qué cambia al limitar el delta?', answer: 'El límite reduce el delta que usa el modelo variable cuando un frame supera el techo elegido. Puede evitar que un hitch desplace demasiado un objeto, pero también hace que ese reloj simulado se quede atrás respecto al tiempo real. El acumulador fijo sigue contabilizando toda la duración del frame.' },
  { question: '¿Es un profiler o sustituye a las pruebas del juego?', answer: 'No. Es un laboratorio determinista de aprendizaje y diseño con números declarados. No mide tu dispositivo, diagnostica un motor, modela el coste de renderizado ni demuestra que un bucle sea correcto para cualquier juego.' },
];

const howTo = [
  { name: 'Elegir el ritmo de frames', text: 'Define los frames por segundo objetivo y añade un pico repetible en milisegundos. Usa la frecuencia para colocar el pico cada cierto número de frames.' },
  { name: 'Definir el paso de simulación', text: 'Elige el timestep fijo en milisegundos. Un valor cercano a 16,667 milisegundos representa una simulación de aproximadamente 60 actualizaciones por segundo.' },
  { name: 'Dar la misma regla de movimiento', text: 'Configura velocidad y duración. Ambos modelos mueven el mismo objeto, así que la diferencia de posición nace de cómo consumen el tiempo transcurrido.' },
  { name: 'Probar un límite de forma deliberada', text: 'Activa el límite de delta y compara el tiempo simulado del modelo variable con el acumulador fijo. Un límite es una decisión con un coste visible, no una corrección gratuita.' },
  { name: 'Leer las evidencias', text: 'Observa las dos pistas, el resumen de divergencia, la línea temporal, la recuperación y la tabla accesible de frames. Cambia una entrada cada vez al enseñar o depurar el diseño.' },
];

const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratorio de delta time y timestep fijo para juegos', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Comparar delta time variable con timestep fijo', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorio-delta-time-y-timestep-fijo-para-juegos',
  title: 'Laboratorio de Delta Time y Timestep Fijo para Juegos',
  description: 'Compara bucles de juego con delta variable y timestep fijo mediante picos de frame repetibles, movimiento simulado, recuperación y deriva temporal visible.',
  ui: {
    controlsTitle: 'Construye el patrón de frames', fpsLabel: 'Tasa de frames objetivo', fpsHint: 'Frames renderizados por segundo', spikeLabel: 'Pico de frame', spikeHint: 'Tiempo extra añadido a los frames con pico', spikeEveryLabel: 'Pico cada cuántos frames', fixedDtLabel: 'Timestep fijo', fixedDtHint: 'Tamaño del paso de simulación', velocityLabel: 'Velocidad del objeto', durationLabel: 'Duración de la prueba', clampLabel: 'Techo del delta', clampToggle: 'Limitar el delta variable', runLabel: 'Ejecutar experimento', resetLabel: 'Restablecer valores', stageKicker: 'El campo de pruebas', stageTitle: 'Dos relojes, un objeto en movimiento', stageCaption: 'Las barras muestran los hitches, las líneas siguen ambas posiciones y la pista inferior aísla la deriva que pueden ocultar los valores finales.', frameTraceLabel: 'Duraciones de frame', positionPlotLabel: 'Posición del objeto', differencePlotLabel: 'Diferencia de posición frente al recorrido fijo', variableLane: 'Delta variable', fixedLane: 'Acumulador fijo', frameCountLabel: 'Frames renderizados', wallTimeLabel: 'Tiempo real', variableTimeLabel: 'Tiempo simulado variable', fixedTimeLabel: 'Tiempo simulado fijo', divergenceLabel: 'Diferencia de posición', stepsLabel: 'Pasos de simulación fijos', diagnosticsTitle: 'Lectura de frames', stableStatus: 'Las dos rutas permanecen alineadas con este patrón.', variableStatus: 'La ruta variable se adelanta porque sus duraciones incluyen los picos.', fixedStatus: 'La ruta fija recupera el tiempo con varios pasos de simulación después de un frame largo.', clampStatus: 'El límite reduce el salto variable y deja ese modelo por detrás del tiempo real transcurrido.', timelineTitle: 'El registro del movimiento', timelineCaption: 'Posición a lo largo del tiempo real transcurrido. La línea discontinua marca pasos fijos iguales.', frameAxis: 'Tiempo real transcurrido', positionAxis: 'Posición del objeto', legendVariable: 'Ruta de delta variable', legendFixed: 'Ruta de timestep fijo', legendSpike: 'Pico de frame', tableTitle: 'Registro de frames accesible', tableFrame: 'Frame', tableWall: 'Tiempo real', tableVariable: 'Posición variable', tableFixed: 'Posición fija', tableDelta: 'Diferencia', modelNote: 'El modelo variable aplica la velocidad una vez con la duración del frame actual. El modelo fijo acumula todo el tiempo real y avanza en pasos iguales. Ninguna ruta es una medición de rendimiento.', privacyDisclosure: 'Tus valores se guardan solo en este navegador para que el experimento esté listo cuando vuelvas. No se envían datos del juego ni telemetría.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'unidades', statusReady: 'Experimento actualizado',
  },
  seo: [
    { type: 'title', level: 2, text: 'Entiende el reloj dentro de un bucle de juego' },
    { type: 'paragraph', html: 'Cada frame renderizado entrega al juego un nuevo tiempo transcurrido. En un bucle de delta variable, el movimiento suele actualizarse como <code>position += velocity × frameTime</code>. Con frames estables, la velocidad media se acerca a la prevista, pero cada actualización puede ser tan grande como el frame que la produjo. Por eso un hitch no es solo una pausa visual: cambia la cantidad de tiempo de juego consumida por esa actualización.' },
    { type: 'title', level: 2, text: 'Compara la integración variable con un acumulador fijo' },
    { type: 'paragraph', html: 'Un bucle de timestep fijo suma la duración de cada frame a un acumulador y consume repetidamente un paso elegido, como <code>16,667 ms</code>. La simulación recibe actualizaciones iguales mientras el render puede mantener otro ritmo. La fracción sobrante queda en el acumulador para el siguiente frame. Cuando llega un frame largo, el bucle fijo ejecuta varias actualizaciones pequeñas para contabilizar el tiempo transcurrido. Conserva el tamaño del paso, pero puede crear un pico de trabajo de recuperación.' },
    { type: 'table', headers: ['Situación', 'Ruta de delta variable', 'Ruta de timestep fijo', 'Decisión que ayuda a tomar'], rows: [['Renderizado estable', 'Una actualización usa cada duración normal', 'Pasos iguales consumen el tiempo acumulado', 'Ambas rutas deberían seguir la misma trayectoria.'], ['Frame largo', 'Una actualización grande puede mover demasiado el objeto', 'Varias actualizaciones fijas recuperan el tiempo', 'Mira la deriva junto al número de pasos de recuperación.'], ['Otra tasa de renderizado', 'El tamaño de actualización cambia con los frames', 'El paso de simulación se mantiene', 'Los pasos fijos reducen la dependencia del render.'], ['Techo del delta', 'Se ignora el tiempo que supera el límite', 'El acumulador recibe la duración completa', 'Limita solo cuando perder tiempo sea aceptable.']] },
    { type: 'title', level: 2, text: 'Observa qué hace realmente un pico de frame' },
    { type: 'paragraph', html: 'A 60 frames por segundo, un frame normal dura aproximadamente <code>16,667 ms</code>. Con un pico adicional de <code>80 ms</code>, un frame pasa a durar unos <code>96,667 ms</code>. El modelo variable consume toda esa duración en una actualización. El modelo fijo consume en cambio unos seis pasos de <code>16,667 ms</code>. El tiempo total transcurrido puede coincidir, aunque el recorrido por la simulación sea diferente.' },
    { type: 'title', level: 2, text: 'Lee juntos la deriva de posición y la recuperación' },
    { type: 'paragraph', html: 'La diferencia de posición es la ruta variable menos la ruta fija. Indica cuánto se han separado las dos políticas de integración, no cuál es automáticamente correcta. El número de recuperación indica cuánto trabajo fijo hizo falta dentro de un único frame renderizado. Una diferencia grande apunta a una divergencia de movimiento visible; muchos pasos de recuperación apuntan a un posible problema de presupuesto de CPU. Están relacionados, pero no son el mismo diagnóstico.' },
    { type: 'title', level: 2, text: 'Trata el límite del delta como una política' },
    { type: 'paragraph', html: 'Un límite puede evitar que una pestaña en pausa, un breakpoint o un hitch grave teletransporte a un personaje o envíe un cuerpo físico a través de la geometría. El coste es que el reloj variable se queda por detrás del tiempo real transcurrido. Si el juego debe conservar el tiempo, usa un acumulador fijo u otra política de recuperación. Si debe mantener los saltos acotados y responder bien, el límite puede ser válido, pero el tiempo perdido debe ser intencionado.' },
    { type: 'title', level: 2, text: 'Elige el bucle según lo que deba proteger' },
    { type: 'table', headers: ['Trabajo del bucle', 'Valor predeterminado útil', 'Motivo'], rows: [['Física, colisiones o gameplay determinista', 'Timestep fijo', 'Los pasos iguales hacen que la simulación dependa menos del ritmo de renderizado.'], ['Movimiento visual simple sin estado acumulado', 'Delta variable', 'La actualización es pequeña y normalmente no necesita una cola de recuperación.'], ['Simulación de gameplay con render suave', 'Actualización fija con interpolación', 'La simulación conserva su paso mientras la presentación oculta el progreso fraccionario.'], ['Recuperación tras un bloqueo grave', 'Política de recuperación acotada', 'Evita convertir un frame malo en trabajo de simulación ilimitado.']] },
    { type: 'title', level: 2, text: 'Usa un flujo de ajuste repetible' },
    { type: 'paragraph', html: 'Empieza sin picos y confirma que ambas rutas coinciden. Añade un hitch repetible y cambia su frecuencia para ver si el error visible se acumula o se estabiliza. Ajusta el paso fijo y observa la cantidad de recuperación antes de cambiar la velocidad. Por último, activa el límite y compara el tiempo simulado variable con el tiempo real. Esta secuencia separa la causa de una divergencia de la política que se usa para contenerla.' },
    { type: 'tip', title: 'Qué no puede demostrar este experimento', html: 'El laboratorio usa duraciones de frame declaradas y velocidad constante, así que explica el comportamiento temporal, pero no mide un dispositivo ni valida un motor. La física real, el muestreo de entrada, la red, la interpolación y el presupuesto de frame pueden cambiar el mejor diseño. Usa el resultado para formular una hipótesis y compruébala en el juego real.' },
  ],
  faq,
  bibliographyTitle: 'Referencias sobre bucles de juego',
  bibliography: bibliographyEntries,
  howTo,
  schemas: [softwareApplication, faqPage, howToSchema],
};
