import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Que montre ce laboratoire de timestep fixe ?', answer: 'Il fait passer le même objet en mouvement dans une boucle à delta variable et dans un accumulateur à pas fixe. Des pics de frame répétables rendent visibles le temps simulé, la dérive de position et les pas de rattrapage, sans lancer de moteur de jeu.' },
  { question: 'Quelle est la différence entre delta variable et timestep fixe ?', answer: 'Le modèle variable avance une fois par frame rendu avec sa durée. Le modèle fixe avance par pas de simulation égaux et utilise un accumulateur pour traiter autant de pas que le temps réel écoulé l exige. Les pas fixes réduisent la dépendance au rythme de rendu, mais une longue frame peut demander davantage de calcul.' },
  { question: 'Que représente l entrée de pic de frame ?', answer: 'Elle ajoute des millisecondes à chaque frame choisie comme pic. Le champ de cadence indique tous les combien de frames le pic apparaît, afin de créer un hitch reproductible plutôt qu une trace aléatoire.' },
  { question: 'Que change le plafonnement du delta ?', answer: 'Le plafond limite le delta utilisé par le modèle variable lorsqu une frame dépasse la valeur choisie. Cela peut empêcher un saut trop grand, mais l horloge simulée de ce modèle prend alors du retard sur le temps réel. L accumulateur fixe comptabilise toujours toute la durée de la frame.' },
  { question: 'Est ce un profiler ou un remplacement des tests de jeu ?', answer: 'Non. C est un laboratoire déterministe d apprentissage et de conception fondé sur des valeurs déclarées. Il ne mesure pas votre appareil, ne diagnostique pas un moteur, ne modélise pas le coût du rendu et ne prouve pas qu une boucle convient à tous les jeux.' },
];
const howTo = [
  { name: 'Choisir le rythme des frames', text: 'Définissez les frames par seconde visées et ajoutez un pic répétable en millisecondes. La cadence place ce pic tous les quelques frames.' },
  { name: 'Définir le pas de simulation', text: 'Choisissez le timestep fixe en millisecondes. Une valeur proche de 16,667 millisecondes représente environ 60 mises à jour par seconde.' },
  { name: 'Donner la même règle de mouvement', text: 'Définissez la vitesse et la durée. Les deux modèles déplacent le même objet, donc la différence vient de leur manière de consommer le temps écoulé.' },
  { name: 'Tester un plafond consciemment', text: 'Activez le plafond du delta et comparez le temps simulé du modèle variable avec l accumulateur fixe. Un plafond est un choix avec un coût visible, pas une correction gratuite.' },
  { name: 'Lire les indices', text: 'Examinez les deux trajectoires, le résumé de divergence, la chronologie, le rattrapage et le tableau de frames accessible. Changez une seule entrée à la fois pour expliquer ou déboguer la boucle.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratoire du delta time et du timestep fixe pour jeux', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Comparer un delta time variable à un timestep fixe', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratoire-delta-time-et-timestep-fixe-jeu', title: 'Laboratoire de Delta Time et Timestep Fixe pour Jeux', description: 'Comparez les boucles de jeu à delta variable et à timestep fixe avec des pics de frame répétables, du mouvement simulé, du rattrapage et une dérive temporelle visible.',
  ui: { controlsTitle: 'Construire le rythme des frames', fpsLabel: 'Cadence cible', fpsHint: 'Frames rendues par seconde', spikeLabel: 'Pic de frame', spikeHint: 'Temps ajouté aux frames en pic', spikeEveryLabel: 'Pic tous les frames', fixedDtLabel: 'Timestep fixe', fixedDtHint: 'Taille égale du pas de simulation', velocityLabel: 'Vitesse de l objet', durationLabel: 'Durée de l expérience', clampLabel: 'Plafond du delta', clampToggle: 'Plafonner le delta variable', runLabel: 'Lancer l expérience', resetLabel: 'Réinitialiser les valeurs', stageKicker: 'Le terrain d essai', stageTitle: 'Deux horloges, un objet en mouvement', stageCaption: 'Les barres montrent les hitches, les lignes suivent les deux positions et la trace basse isole la dérive que les valeurs finales peuvent cacher.', frameTraceLabel: 'Durées de frame', positionPlotLabel: 'Position de l objet', differencePlotLabel: 'Différence de position avec le chemin fixe', variableLane: 'Delta variable', fixedLane: 'Accumulateur fixe', frameCountLabel: 'Frames rendues', wallTimeLabel: 'Temps réel', variableTimeLabel: 'Temps simulé variable', fixedTimeLabel: 'Temps simulé fixe', divergenceLabel: 'Différence de position', stepsLabel: 'Pas de simulation fixes', diagnosticsTitle: 'Lecture des frames', stableStatus: 'Les deux chemins restent alignés pour ce motif.', variableStatus: 'Le chemin variable prend de l avance car ses durées incluent les pics.', fixedStatus: 'Le chemin fixe rattrape son retard en plusieurs pas après une longue frame.', clampStatus: 'Le plafond réduit le saut variable et laisse ce modèle derrière le temps réel écoulé.', timelineTitle: 'Le registre du mouvement', timelineCaption: 'Position selon le temps réel écoulé. Une ligne en pointillé marque les pas fixes égaux.', frameAxis: 'Temps réel écoulé', positionAxis: 'Position de l objet', legendVariable: 'Chemin à delta variable', legendFixed: 'Chemin à timestep fixe', legendSpike: 'Pic de frame', tableTitle: 'Registre des frames accessible', tableFrame: 'Frame', tableWall: 'Temps réel', tableVariable: 'Position variable', tableFixed: 'Position fixe', tableDelta: 'Différence', modelNote: 'Le modèle variable applique la vitesse une fois avec la durée de la frame actuelle. Le modèle fixe accumule tout le temps réel et avance par pas égaux. Aucun chemin ne mesure les performances.', privacyDisclosure: 'Vos valeurs sont enregistrées uniquement dans ce navigateur pour retrouver l expérience prête à votre retour. Aucune donnée de jeu ni télémétrie n est envoyée.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'unités', statusReady: 'Expérience mise à jour' },
  seo: [
    { type: 'title', level: 2, text: 'Comprendre l horloge d une boucle de jeu' },
    { type: 'paragraph', html: 'Chaque frame rendue fournit au jeu un nouveau temps écoulé. Dans une boucle à delta variable, le mouvement est souvent mis à jour avec <code>position += velocity × frameTime</code>. Quand les frames sont régulières, la vitesse moyenne reste proche de la valeur voulue, mais une mise à jour peut devenir aussi grande que la frame qui l a produite. Un hitch n est donc pas seulement une pause visuelle: il change la quantité de temps de jeu consommée par cette mise à jour.' },
    { type: 'title', level: 2, text: 'Comparer l intégration variable à un accumulateur fixe' },
    { type: 'paragraph', html: 'Une boucle à timestep fixe ajoute la durée de chaque frame à un accumulateur, puis consomme plusieurs fois un pas choisi comme <code>16,667 ms</code>. La simulation reçoit des mises à jour égales tandis que le rendu peut garder un autre rythme. La fraction restante reste dans l accumulateur pour la frame suivante. Lorsqu une longue frame arrive, la boucle fixe exécute plusieurs petites mises à jour pour couvrir le temps écoulé. La taille du pas reste stable, mais un rattrapage peut créer une pointe de travail.' },
    { type: 'table', headers: ['Situation', 'Chemin à delta variable', 'Chemin à timestep fixe', 'Décision à envisager'], rows: [['Rendu régulier', 'Une mise à jour utilise chaque durée normale', 'Des pas égaux consomment le temps accumulé', 'Les deux chemins devraient rester proches.'], ['Longue frame', 'Une grande mise à jour peut déplacer trop loin un objet', 'Plusieurs mises à jour fixes rattrapent le temps écoulé', 'Lire la dérive avec le nombre de pas de rattrapage.'], ['Cadence de rendu différente', 'La taille de mise à jour change avec la cadence', 'Le pas de simulation reste identique', 'Les pas fixes réduisent la dépendance au rendu.'], ['Plafond du delta', 'Le temps au-dessus du plafond est ignoré', 'L accumulateur reçoit toute la durée de la frame', 'Ne plafonner que si perdre du temps est acceptable.']] },
    { type: 'title', level: 2, text: 'Voir l effet réel d un pic de frame' },
    { type: 'paragraph', html: 'À 60 frames par seconde, une frame normale dure environ <code>16,667 ms</code>. Avec un pic supplémentaire de <code>80 ms</code>, une frame dure environ <code>96,667 ms</code>. Le modèle variable consomme toute cette durée en une mise à jour. Le modèle fixe consomme plutôt environ six pas de <code>16,667 ms</code>. Le temps écoulé total peut correspondre alors que le parcours dans la simulation est différent.' },
    { type: 'title', level: 2, text: 'Lire ensemble dérive de position et rattrapage' },
    { type: 'paragraph', html: 'La différence de position est le chemin variable moins le chemin fixe. Elle montre la séparation entre les deux politiques d intégration, sans dire automatiquement laquelle est correcte. Le nombre de rattrapage indique le travail fixe nécessaire dans une seule frame rendue. Une grande différence suggère une divergence de mouvement visible ; un grand nombre de pas suggère un risque pour le budget CPU. Ces signaux sont liés, mais ne donnent pas le même diagnostic.' },
    { type: 'title', level: 2, text: 'Traiter le plafonnement du delta comme une politique' },
    { type: 'paragraph', html: 'Un plafond peut empêcher qu un onglet en pause, un breakpoint ou un hitch sévère téléporte un personnage ou fasse traverser la géométrie à un corps physique. En contrepartie, l horloge variable prend du retard sur le temps réel écoulé. Si le jeu doit préserver le timing, préférez un accumulateur fixe ou une autre politique de récupération. Si le jeu doit rester borné et réactif, un plafond peut convenir, mais le temps perdu doit être voulu.' },
    { type: 'title', level: 2, text: 'Choisir la boucle selon ce qu elle protège' },
    { type: 'table', headers: ['Travail de la boucle', 'Choix utile par défaut', 'Pourquoi'], rows: [['Physique, collisions ou gameplay déterministe', 'Timestep fixe', 'Des pas égaux rendent la simulation moins dépendante du rythme de rendu.'], ['Mouvement visuel simple sans état accumulé', 'Delta variable', 'La mise à jour est petite et ne demande généralement pas de file de rattrapage.'], ['Simulation de gameplay avec rendu fluide', 'Mise à jour fixe et interpolation', 'La simulation garde son pas pendant que la présentation masque la fraction restante.'], ['Récupération après un arrêt sévère', 'Politique de rattrapage bornée', 'Un mauvais frame ne doit pas créer un travail de simulation sans limite.']] },
    { type: 'title', level: 2, text: 'Suivre une méthode de réglage reproductible' },
    { type: 'paragraph', html: 'Commencez sans pics et vérifiez que les deux chemins correspondent. Ajoutez un hitch reproductible, puis changez sa cadence pour voir si l erreur visible s accumule ou se stabilise. Ajustez le pas fixe et observez le rattrapage avant de modifier la vitesse. Activez enfin le plafond et comparez le temps simulé variable au temps réel. Cette séquence sépare la cause d une divergence de la politique qui cherche à la contenir.' },
    { type: 'tip', title: 'Ce que cette expérience ne peut pas prouver', html: 'Le laboratoire utilise des durées de frame déclarées et une vitesse constante. Il explique donc le comportement temporel, mais ne mesure pas un appareil et ne valide pas un moteur. La physique réelle, l échantillonnage des entrées, le réseau, l interpolation et le budget de frame peuvent changer le meilleur choix. Utilisez le résultat pour former une hypothèse, puis vérifiez-la dans le jeu réel.' },
  ],
  faq, bibliographyTitle: 'Références sur les boucles de jeu', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
