import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Apa yang ditunjukkan laboratorium timestep tetap ini?', answer: 'Laboratorium ini menjalankan objek bergerak yang sama melalui loop delta variabel dan akumulator timestep tetap. Spike frame yang berulang membuat waktu simulasi, selisih posisi, dan langkah pengejaran dapat dilihat tanpa menjalankan game engine.' },
  { question: 'Apa perbedaan delta variabel dan timestep tetap?', answer: 'Model variabel maju sekali pada setiap frame yang dirender menggunakan durasi frame tersebut. Model tetap maju dalam langkah simulasi yang sama besar dan memakai akumulator untuk memproses langkah sesuai waktu nyata yang berlalu. Langkah tetap mengurangi ketergantungan simulasi pada frame rate, tetapi frame panjang dapat menambah pekerjaan pengejaran.' },
  { question: 'Apa arti input spike frame?', answer: 'Input itu menambahkan milidetik ekstra ke setiap frame yang dipilih sebagai spike. Kolom frekuensi menentukan setiap berapa frame spike muncul, sehingga kamu dapat membuat pola hitch yang berulang dan dapat dibandingkan.' },
  { question: 'Apa yang berubah saat delta dibatasi?', answer: 'Batas mengurangi delta yang dipakai model variabel ketika frame melebihi nilai maksimum. Ini dapat mencegah lompatan yang terlalu besar, tetapi waktu simulasi model itu tertinggal dari waktu nyata. Akumulator tetap tetap menghitung seluruh durasi frame.' },
  { question: 'Apakah ini profiler atau pengganti playtest?', answer: 'Bukan. Ini laboratorium pembelajaran dan desain deterministik dengan angka yang ditentukan. Laboratorium ini tidak mengukur perangkat, mendiagnosis engine, memodelkan biaya render, atau membuktikan bahwa satu loop cocok untuk semua game.' },
];
const howTo = [
  { name: 'Pilih ritme frame', text: 'Atur frame per detik target dan tambahkan spike berulang dalam milidetik. Gunakan frekuensi untuk menempatkan spike setiap sejumlah frame.' },
  { name: 'Atur langkah simulasi', text: 'Pilih timestep tetap dalam milidetik. Nilai sekitar 16,667 milidetik mewakili sekitar 60 pembaruan simulasi per detik.' },
  { name: 'Gunakan aturan gerak yang sama', text: 'Atur kecepatan dan durasi. Kedua model menggerakkan objek yang sama, jadi selisih posisi berasal dari cara masing-masing mengonsumsi waktu.' },
  { name: 'Uji batas dengan sengaja', text: 'Aktifkan batas delta lalu bandingkan waktu simulasi variabel dengan akumulator tetap. Batas adalah keputusan dengan biaya yang terlihat, bukan perbaikan gratis.' },
  { name: 'Baca buktinya', text: 'Periksa kedua jalur, ringkasan selisih, garis waktu, perilaku pengejaran, dan tabel frame yang mudah diakses. Ubah satu input saja setiap kali saat mengajar atau men-debug loop.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratorium game delta time dan timestep tetap', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Membandingkan delta time variabel dengan timestep tetap', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorium-delta-time-dan-timestep-tetap-game', title: 'Laboratorium Delta Time dan Timestep Tetap Game', description: 'Bandingkan loop game delta variabel dan timestep tetap dengan spike frame berulang, gerakan simulasi, langkah pengejaran, dan selisih waktu yang terlihat.',
  ui: { controlsTitle: 'Buat pola frame', fpsLabel: 'Frame rate target', fpsHint: 'Frame yang dirender per detik', spikeLabel: 'Spike frame', spikeHint: 'Waktu tambahan pada frame spike', spikeEveryLabel: 'Spike setiap frame', fixedDtLabel: 'Timestep tetap', fixedDtHint: 'Ukuran langkah simulasi yang sama', velocityLabel: 'Kecepatan objek', durationLabel: 'Durasi percobaan', clampLabel: 'Batas delta', clampToggle: 'Batasi delta variabel', runLabel: 'Jalankan percobaan', resetLabel: 'Atur ulang nilai', stageKicker: 'Arena pengujian', stageTitle: 'Dua jam, satu objek bergerak', stageCaption: 'Batang menunjukkan hitch, garis mengikuti kedua posisi, dan jejak bawah mengisolasi selisih yang dapat disembunyikan nilai akhir.', frameTraceLabel: 'Durasi frame', positionPlotLabel: 'Posisi objek', differencePlotLabel: 'Selisih posisi dari jalur tetap', variableLane: 'Delta variabel', fixedLane: 'Akumulator tetap', frameCountLabel: 'Frame yang dirender', wallTimeLabel: 'Waktu nyata', variableTimeLabel: 'Waktu simulasi variabel', fixedTimeLabel: 'Waktu simulasi tetap', divergenceLabel: 'Selisih posisi', stepsLabel: 'Langkah simulasi tetap', diagnosticsTitle: 'Pembacaan frame', stableStatus: 'Kedua jalur tetap sejajar untuk pola ini.', variableStatus: 'Jalur variabel bergerak lebih cepat karena durasi frame mencakup spike.', fixedStatus: 'Jalur tetap mengejar dengan beberapa langkah simulasi setelah frame panjang.', clampStatus: 'Batas mengurangi lompatan variabel dan membuat model itu tertinggal dari waktu nyata yang berlalu.', timelineTitle: 'Buku gerak', timelineCaption: 'Posisi terhadap waktu nyata yang berlalu. Garis putus-putus menandai langkah tetap yang sama.', frameAxis: 'Waktu nyata yang berlalu', positionAxis: 'Posisi objek', legendVariable: 'Jalur delta variabel', legendFixed: 'Jalur timestep tetap', legendSpike: 'Spike frame', tableTitle: 'Buku frame yang mudah diakses', tableFrame: 'Frame', tableWall: 'Waktu nyata', tableVariable: 'Posisi variabel', tableFixed: 'Posisi tetap', tableDelta: 'Selisih', modelNote: 'Model variabel menerapkan kecepatan sekali dengan durasi frame saat ini. Model tetap mengakumulasi seluruh waktu nyata dan maju dalam langkah yang sama. Tidak ada jalur yang merupakan pengukuran performa.', privacyDisclosure: 'Nilai kamu disimpan hanya di browser ini agar percobaan siap saat kamu kembali. Tidak ada data game atau telemetri yang dikirim.', unitMs: 'ms', unitSeconds: 'dtk', unitPixels: 'unit', statusReady: 'Percobaan diperbarui' },
  seo: [
    { type: 'title', level: 2, text: 'Pahami jam di dalam loop game' },
    { type: 'paragraph', html: 'Setiap frame yang dirender memberikan waktu berlalu yang baru kepada game. Dalam loop delta variabel, gerakan biasanya diperbarui sebagai <code>position += velocity × frameTime</code>. Saat frame stabil, kecepatan rata-rata mendekati nilai yang diinginkan, tetapi satu pembaruan bisa sebesar frame yang memicunya. Hitch bukan sekadar jeda visual: hitch mengubah jumlah waktu game yang dikonsumsi oleh pembaruan itu.' },
    { type: 'title', level: 2, text: 'Bandingkan integrasi variabel dengan akumulator tetap' },
    { type: 'paragraph', html: 'Loop timestep tetap menambahkan durasi setiap frame ke akumulator, lalu berulang kali memakai langkah seperti <code>16,667 ms</code>. Simulasi menerima pembaruan yang sama besar, sementara renderer dapat berjalan dengan ritme berbeda. Sisa pecahan disimpan untuk frame berikutnya. Saat frame panjang muncul, loop tetap menjalankan beberapa pembaruan kecil untuk menghitung waktu yang berlalu. Ukuran langkah tetap stabil, tetapi dapat muncul lonjakan kerja pengejaran.' },
    { type: 'table', headers: ['Situasi', 'Jalur delta variabel', 'Jalur timestep tetap', 'Keputusan yang dipertimbangkan'], rows: [['Render stabil', 'Satu pembaruan memakai setiap durasi normal', 'Langkah yang sama memakai waktu terakumulasi', 'Kedua jalur seharusnya mengikuti gerakan yang sama.'], ['Frame panjang', 'Satu pembaruan besar dapat menggerakkan objek terlalu jauh', 'Beberapa pembaruan tetap mengejar waktu', 'Baca selisih bersama jumlah langkah pengejaran.'], ['Frame rate berbeda', 'Ukuran pembaruan berubah mengikuti frame rate', 'Langkah simulasi tetap sama', 'Langkah tetap mengurangi ketergantungan pada render.'], ['Batas delta', 'Waktu di atas batas diabaikan', 'Akumulator menerima seluruh durasi frame', 'Batasi hanya jika kehilangan waktu dapat diterima.']] },
    { type: 'title', level: 2, text: 'Lihat dampak sebenarnya dari spike frame' },
    { type: 'paragraph', html: 'Pada 60 frame per detik, frame normal berdurasi sekitar <code>16,667 ms</code>. Dengan spike tambahan <code>80 ms</code>, satu frame menjadi sekitar <code>96,667 ms</code>. Model variabel memakai seluruh durasi itu dalam satu pembaruan. Model tetap memakai kira-kira enam langkah <code>16,667 ms</code>. Total waktu berlalu bisa sama, tetapi jalur yang ditempuh simulasi berbeda.' },
    { type: 'title', level: 2, text: 'Baca selisih posisi bersama pengejaran' },
    { type: 'paragraph', html: 'Selisih posisi adalah jalur variabel dikurangi jalur tetap. Ini menunjukkan seberapa jauh kebijakan integrasi terpisah, bukan model mana yang otomatis benar. Jumlah pengejaran menunjukkan pekerjaan tetap yang diperlukan dalam satu frame render. Selisih besar mengarah pada perbedaan gerak yang terlihat; banyak langkah mengarah pada kemungkinan masalah anggaran CPU. Keduanya terkait, tetapi bukan diagnosis yang sama.' },
    { type: 'title', level: 2, text: 'Perlakukan pembatasan delta sebagai kebijakan' },
    { type: 'paragraph', html: 'Batas dapat mencegah tab yang dijeda, breakpoint, atau hitch berat membuat karakter berpindah jauh atau tubuh fisik menembus geometri. Konsekuensinya, jam variabel tertinggal dari waktu nyata. Jika game harus mempertahankan waktu, gunakan akumulator tetap atau kebijakan pemulihan lain. Jika game harus membatasi lompatan dan tetap responsif, batas mungkin sesuai, tetapi waktu yang hilang harus disengaja.' },
    { type: 'title', level: 2, text: 'Pilih loop berdasarkan tugas yang dilindunginya' },
    { type: 'table', headers: ['Tugas loop game', 'Pilihan awal yang berguna', 'Alasan'], rows: [['Fisika, tabrakan, atau gameplay deterministik', 'Timestep tetap', 'Langkah yang sama membuat simulasi kurang bergantung pada ritme render.'], ['Gerakan visual sederhana tanpa state terakumulasi', 'Delta variabel', 'Pembaruan kecil dan biasanya tidak memerlukan antrean pengejaran.'], ['Simulasi gameplay dengan render halus', 'Update tetap dengan interpolasi', 'Simulasi mempertahankan langkah sementara tampilan menyembunyikan pecahan gerak.'], ['Pemulihan setelah berhenti berat', 'Kebijakan pengejaran terbatas', 'Cegah satu frame buruk menjadi pekerjaan simulasi tanpa batas.']] },
    { type: 'title', level: 2, text: 'Gunakan alur penyetelan yang dapat diulang' },
    { type: 'paragraph', html: 'Mulai tanpa spike dan pastikan kedua jalur cocok. Tambahkan hitch berulang, lalu ubah frekuensinya untuk melihat apakah kesalahan visual bertambah atau stabil. Sesuaikan langkah tetap dan perhatikan jumlah pengejaran sebelum mengubah kecepatan. Terakhir, aktifkan batas dan bandingkan waktu simulasi variabel dengan waktu nyata. Urutan ini memisahkan penyebab selisih dari kebijakan yang digunakan untuk menahannya.' },
    { type: 'tip', title: 'Hal yang tidak dapat dibuktikan percobaan ini', html: 'Laboratorium memakai durasi frame yang ditentukan dan kecepatan konstan, jadi ia menjelaskan perilaku waktu, bukan mengukur perangkat atau memvalidasi engine. Fisika nyata, pengambilan input, jaringan, interpolasi, dan anggaran frame dapat mengubah desain terbaik. Gunakan hasilnya sebagai hipotesis lalu periksa hipotesis itu di game yang sebenarnya.' },
  ],
  faq, bibliographyTitle: 'Referensi loop game', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
