import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Che cosa dimostra questo laboratorio sul timestep fisso?', answer: 'Esegue lo stesso oggetto in movimento con un ciclo a delta variabile e con un accumulatore a timestep fisso. I picchi di frame ripetibili rendono visibili tempo simulato, deriva della posizione e passi di recupero senza avviare un motore di gioco.' },
  { question: 'Qual è la differenza tra delta variabile e timestep fisso?', answer: 'Il modello variabile avanza una volta per ogni frame renderizzato usando la sua durata. Il modello fisso avanza con passi di simulazione uguali e usa un accumulatore per elaborare i passi richiesti dal tempo reale trascorso. I passi fissi riducono la dipendenza dal frame rate, ma un frame lungo può richiedere lavoro di recupero.' },
  { question: 'Che cosa rappresenta l input del picco di frame?', answer: 'Aggiunge millisecondi extra a ogni frame scelto come picco. Il campo della frequenza decide ogni quanti frame compare, così puoi creare un hitch ripetibile invece di usare una traccia casuale.' },
  { question: 'Che cosa cambia il limite del delta?', answer: 'Il limite restringe il delta usato dal modello variabile quando un frame supera il tetto scelto. Può evitare uno spostamento enorme, ma fa restare quell orologio simulato indietro rispetto al tempo reale. L accumulatore fisso continua a considerare tutta la durata del frame.' },
  { question: 'È un profiler o sostituisce i test del gioco?', answer: 'No. È un laboratorio deterministico per imparare e progettare usando numeri dichiarati. Non misura il tuo dispositivo, non diagnostica un motore, non simula il costo del rendering e non dimostra che un ciclo sia corretto per ogni gioco.' },
];
const howTo = [
  { name: 'Scegliere il ritmo dei frame', text: 'Imposta i frame al secondo obiettivo e aggiungi un picco ripetibile in millisecondi. Usa la frequenza per collocarlo ogni determinato numero di frame.' },
  { name: 'Impostare il passo di simulazione', text: 'Scegli il timestep fisso in millisecondi. Un valore vicino a 16,667 millisecondi rappresenta circa 60 aggiornamenti di simulazione al secondo.' },
  { name: 'Dare la stessa regola di movimento', text: 'Imposta velocità e durata. I due modelli muovono lo stesso oggetto, quindi la differenza di posizione nasce da come consumano il tempo trascorso.' },
  { name: 'Provare un limite in modo consapevole', text: 'Attiva il limite del delta e confronta il tempo simulato variabile con l accumulatore fisso. Un limite è una scelta con un costo visibile, non una correzione gratuita.' },
  { name: 'Leggere le prove', text: 'Controlla i due percorsi, il riepilogo della divergenza, la sequenza temporale, il recupero e la tabella accessibile dei frame. Cambia un solo input alla volta per spiegare o correggere il ciclo.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratorio game delta time e timestep fisso', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Confrontare delta time variabile e timestep fisso', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorio-delta-time-e-timestep-fisso-giochi', title: 'Laboratorio Delta Time e Timestep Fisso per Giochi', description: 'Confronta i cicli di gioco a delta variabile e timestep fisso con picchi di frame ripetibili, movimento simulato, passi di recupero e deriva temporale visibile.',
  ui: { controlsTitle: 'Costruisci il ritmo dei frame', fpsLabel: 'Frame rate obiettivo', fpsHint: 'Frame renderizzati al secondo', spikeLabel: 'Picco di frame', spikeHint: 'Tempo extra aggiunto ai frame di picco', spikeEveryLabel: 'Picco ogni frame', fixedDtLabel: 'Timestep fisso', fixedDtHint: 'Dimensione del passo di simulazione', velocityLabel: 'Velocità dell oggetto', durationLabel: 'Durata dell esperimento', clampLabel: 'Tetto del delta', clampToggle: 'Limita il delta variabile', runLabel: 'Esegui esperimento', resetLabel: 'Ripristina valori', stageKicker: 'Il campo di prova', stageTitle: 'Due orologi, un oggetto in movimento', stageCaption: 'Le barre mostrano gli hitch, le linee seguono le due posizioni e la traccia inferiore isola la deriva che i valori finali possono nascondere.', frameTraceLabel: 'Durate dei frame', positionPlotLabel: 'Posizione dell oggetto', differencePlotLabel: 'Differenza di posizione rispetto al percorso fisso', variableLane: 'Delta variabile', fixedLane: 'Accumulatore fisso', frameCountLabel: 'Frame renderizzati', wallTimeLabel: 'Tempo reale', variableTimeLabel: 'Tempo simulato variabile', fixedTimeLabel: 'Tempo simulato fisso', divergenceLabel: 'Differenza di posizione', stepsLabel: 'Passi di simulazione fissi', diagnosticsTitle: 'Lettura dei frame', stableStatus: 'I due percorsi restano allineati con questo schema.', variableStatus: 'Il percorso variabile va avanti perché le sue durate includono i picchi.', fixedStatus: 'Il percorso fisso recupera con più passi dopo un frame lungo.', clampStatus: 'Il limite riduce il salto variabile e lascia quel modello indietro rispetto al tempo reale trascorso.', timelineTitle: 'Il registro del movimento', timelineCaption: 'Posizione rispetto al tempo reale trascorso. Una linea tratteggiata indica passi fissi uguali.', frameAxis: 'Tempo reale trascorso', positionAxis: 'Posizione dell oggetto', legendVariable: 'Percorso a delta variabile', legendFixed: 'Percorso a timestep fisso', legendSpike: 'Picco di frame', tableTitle: 'Registro accessibile dei frame', tableFrame: 'Frame', tableWall: 'Tempo reale', tableVariable: 'Posizione variabile', tableFixed: 'Posizione fissa', tableDelta: 'Differenza', modelNote: 'Il modello variabile applica la velocità una volta usando la durata del frame attuale. Il modello fisso accumula tutto il tempo reale e avanza a passi uguali. Nessun percorso è una misura delle prestazioni.', privacyDisclosure: 'I tuoi valori vengono salvati solo in questo browser, così l esperimento è pronto quando ritorni. Nessun dato di gioco o telemetria viene inviato.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'unità', statusReady: 'Esperimento aggiornato' },
  seo: [
    { type: 'title', level: 2, text: 'Capire l orologio dentro un ciclo di gioco' },
    { type: 'paragraph', html: 'Ogni frame renderizzato fornisce al gioco un nuovo tempo trascorso. In un ciclo a delta variabile, il movimento viene spesso aggiornato come <code>position += velocity × frameTime</code>. Quando i frame sono regolari, la velocità media resta vicina a quella desiderata, ma un singolo aggiornamento diventa grande quanto il frame che lo ha prodotto. Un hitch quindi non è solo una pausa visiva: cambia la quantità di tempo di gioco consumata da quell aggiornamento.' },
    { type: 'title', level: 2, text: 'Confrontare l integrazione variabile con un accumulatore fisso' },
    { type: 'paragraph', html: 'Un ciclo a timestep fisso somma ogni durata di frame a un accumulatore, poi consuma ripetutamente un passo scelto come <code>16,667 ms</code>. La simulazione riceve aggiornamenti uguali mentre il rendering può mantenere un ritmo diverso. La frazione residua resta nell accumulatore per il frame successivo. Quando arriva un frame lungo, il ciclo fisso esegue più aggiornamenti piccoli per coprire il tempo trascorso. Il passo resta stabile, ma può comparire un picco di lavoro di recupero.' },
    { type: 'table', headers: ['Situazione', 'Percorso a delta variabile', 'Percorso a timestep fisso', 'Decisione da valutare'], rows: [['Rendering regolare', 'Un aggiornamento usa ogni durata normale', 'Passi uguali consumano il tempo accumulato', 'I due percorsi dovrebbero restare vicini.'], ['Frame lungo', 'Un aggiornamento grande può spostare troppo un oggetto', 'Più aggiornamenti fissi recuperano il tempo', 'Osserva deriva e numero di passi insieme.'], ['Frame rate diverso', 'La dimensione dell aggiornamento cambia', 'Il passo di simulazione resta uguale', 'I passi fissi riducono la dipendenza dal rendering.'], ['Tetto del delta', 'Il tempo oltre il limite viene ignorato', 'L accumulatore riceve la durata completa', 'Limita solo se perdere tempo è accettabile.']] },
    { type: 'title', level: 2, text: 'Vedere l effetto reale di un picco di frame' },
    { type: 'paragraph', html: 'A 60 frame al secondo, un frame regolare dura circa <code>16,667 ms</code>. Con un picco aggiuntivo di <code>80 ms</code>, un frame dura circa <code>96,667 ms</code>. Il modello variabile consuma tutta questa durata in un aggiornamento. Il modello fisso consuma invece circa sei passi da <code>16,667 ms</code>. Il tempo totale trascorso può coincidere, anche se il percorso nella simulazione è diverso.' },
    { type: 'title', level: 2, text: 'Leggere insieme deriva della posizione e recupero' },
    { type: 'paragraph', html: 'La differenza di posizione è il percorso variabile meno quello fisso. Mostra quanto si sono separate le due politiche di integrazione, non quale sia automaticamente corretta. Il conteggio del recupero mostra quanto lavoro fisso è servito in un solo frame renderizzato. Una differenza grande indica una divergenza di movimento visibile; molti passi indicano un possibile problema di budget CPU. Sono segnali collegati, ma non la stessa diagnosi.' },
    { type: 'title', level: 2, text: 'Trattare il limite del delta come una politica' },
    { type: 'paragraph', html: 'Un limite può impedire che una scheda in pausa, un breakpoint o un hitch grave teletrasporti un personaggio o faccia attraversare la geometria a un corpo fisico. Il costo è che l orologio variabile resta indietro rispetto al tempo reale. Se il gioco deve conservare i tempi, usa un accumulatore fisso o un altra politica di recupero. Se deve mantenere salti limitati e restare reattivo, il limite può essere valido, ma il tempo perso deve essere intenzionale.' },
    { type: 'title', level: 2, text: 'Scegliere il ciclo in base a ciò che protegge' },
    { type: 'table', headers: ['Lavoro del ciclo', 'Scelta utile di base', 'Motivo'], rows: [['Fisica, collisioni o gameplay deterministico', 'Timestep fisso', 'I passi uguali rendono la simulazione meno dipendente dal ritmo di rendering.'], ['Movimento visivo semplice senza stato accumulato', 'Delta variabile', 'L aggiornamento è piccolo e di solito non richiede una coda di recupero.'], ['Simulazione di gameplay con rendering fluido', 'Update fisso con interpolazione', 'La simulazione conserva il passo mentre la presentazione nasconde la frazione restante.'], ['Recupero dopo un blocco grave', 'Politica di recupero limitata', 'Evita di trasformare un frame cattivo in lavoro di simulazione illimitato.']] },
    { type: 'title', level: 2, text: 'Usare un flusso di regolazione ripetibile' },
    { type: 'paragraph', html: 'Inizia senza picchi e verifica che i due percorsi coincidano. Aggiungi un hitch ripetibile e cambia la sua frequenza per vedere se l errore visibile cresce o si stabilizza. Regola il passo fisso e osserva il recupero prima di cambiare la velocità. Infine attiva il limite e confronta il tempo simulato variabile con il tempo reale. Questa sequenza separa la causa di una divergenza dalla politica usata per contenerla.' },
    { type: 'tip', title: 'Che cosa non può dimostrare questo esperimento', html: 'Il laboratorio usa durate di frame dichiarate e velocità costante, quindi spiega il comportamento temporale ma non misura un dispositivo né valida un motore. Fisica reale, campionamento degli input, rete, interpolazione e budget di frame possono cambiare la scelta migliore. Usa il risultato per formulare un ipotesi e poi verificala nel gioco reale.' },
  ],
  faq, bibliographyTitle: 'Riferimenti sui cicli di gioco', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
