import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Wat laat dit laboratorium voor een vaste timestep zien?', answer: 'Het voert hetzelfde bewegende object door een lus met variabele delta en door een accumulator met vaste timestep. Herhaalbare framepieken maken gesimuleerde tijd, positiedrift en inhaalstappen zichtbaar zonder een game-engine te starten.' },
  { question: 'Wat is het verschil tussen variabele delta en vaste timestep?', answer: 'Het variabele model werkt eenmaal per gerenderd frame met de duur van dat frame. Het vaste model werkt met gelijke simulatiestappen en gebruikt een accumulator om de stappen te verwerken die de verstreken echte tijd vereist. Vaste stappen verminderen de afhankelijkheid van de renderfrequentie, maar een lang frame kan extra inhaalwerk veroorzaken.' },
  { question: 'Wat stelt de invoer voor een framepiek voor?', answer: 'De invoer voegt extra milliseconden toe aan elk geselecteerd piekframe. Met het interval bepaal je na hoeveel frames de piek verschijnt, zodat je een herhaalbaar hitchpatroon kunt onderzoeken.' },
  { question: 'Wat verandert delta begrenzen?', answer: 'De bovengrens beperkt de delta die het variabele model gebruikt wanneer een frame langer is dan de gekozen grens. Dat kan een te grote sprong voorkomen, maar de gesimuleerde klok loopt dan achter op de echte tijd. De vaste accumulator blijft de volledige frameduur verwerken.' },
  { question: 'Is dit een profiler of vervangt het playtesten?', answer: 'Nee. Het is een deterministisch leer- en ontwerplaboratorium met opgegeven getallen. Het meet geen apparaat, diagnosticeert geen engine, modelleert geen renderkosten en bewijst niet dat één lus voor elk spel geschikt is.' },
];
const howTo = [
  { name: 'Kies het frameritme', text: 'Stel de gewenste frames per seconde in en voeg een herhaalbare piek in milliseconden toe. Gebruik het interval om de piek elke gekozen hoeveelheid frames te plaatsen.' },
  { name: 'Stel de simulatiestap in', text: 'Kies de vaste timestep in milliseconden. Een waarde rond 16,667 milliseconden staat voor ongeveer 60 simulatie-updates per seconde.' },
  { name: 'Geef beide werelden dezelfde bewegingsregel', text: 'Stel snelheid en duur in. Beide modellen bewegen hetzelfde object, dus het positieverschil ontstaat door hun omgang met verstreken tijd.' },
  { name: 'Test een begrenzing bewust', text: 'Schakel de deltabegrenzing in en vergelijk de variabele simulatietijd met de vaste accumulator. Een begrenzing is een keuze met zichtbare kosten, geen gratis correctie.' },
  { name: 'Lees het bewijs', text: 'Bekijk de twee paden, de divergentiesamenvatting, de tijdlijn, het inhaalgedrag en de toegankelijke frametabel. Verander tijdens uitleg of foutzoeken één invoer tegelijk.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Game delta time en vaste timestep laboratorium', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Variabele delta time vergelijken met vaste timestep', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'game-delta-time-en-vaste-timestep-laboratorium', title: 'Game Delta Time en Vaste Timestep Laboratorium', description: 'Vergelijk game-lussen met variabele delta en vaste timestep met herhaalbare framepieken, gesimuleerde beweging, inhaalstappen en zichtbare tijdsdrift.',
  ui: { controlsTitle: 'Bouw het framemotief', fpsLabel: 'Doelframerate', fpsHint: 'Gerenderde frames per seconde', spikeLabel: 'Framepiek', spikeHint: 'Extra tijd voor piekframes', spikeEveryLabel: 'Piek elke frames', fixedDtLabel: 'Vaste timestep', fixedDtHint: 'Gelijke grootte van de simulatiestap', velocityLabel: 'Snelheid van object', durationLabel: 'Duur van experiment', clampLabel: 'Delta-plafond', clampToggle: 'Variabele delta begrenzen', runLabel: 'Experiment uitvoeren', resetLabel: 'Waarden herstellen', stageKicker: 'Het proefveld', stageTitle: 'Twee klokken, één bewegend object', stageCaption: 'Balken tonen de hitches, lijnen volgen beide posities en het onderste spoor maakt de drift zichtbaar die eindwaarden kunnen verbergen.', frameTraceLabel: 'Frameduren', positionPlotLabel: 'Objectpositie', differencePlotLabel: 'Positieverschil met vast pad', variableLane: 'Variabele delta', fixedLane: 'Vaste accumulator', frameCountLabel: 'Gerenderde frames', wallTimeLabel: 'Echte tijd', variableTimeLabel: 'Variabele simulatietijd', fixedTimeLabel: 'Vaste simulatietijd', divergenceLabel: 'Positieverschil', stepsLabel: 'Vaste simulatiestappen', diagnosticsTitle: 'Framelezing', stableStatus: 'De twee paden blijven voor dit patroon gelijk lopen.', variableStatus: 'Het variabele pad loopt voor omdat de frameduren de pieken bevatten.', fixedStatus: 'Het vaste pad haalt na een lang frame in met meerdere simulatiestappen.', clampStatus: 'De begrenzing verkleint de variabele sprong en laat dit model achterlopen op de verstreken echte tijd.', timelineTitle: 'Het bewegingsregister', timelineCaption: 'Positie over verstreken echte tijd. Een stippellijn markeert gelijke vaste stappen.', frameAxis: 'Verstreken echte tijd', positionAxis: 'Objectpositie', legendVariable: 'Variabel deltapad', legendFixed: 'Pad met vaste timestep', legendSpike: 'Framepiek', tableTitle: 'Toegankelijk frameregister', tableFrame: 'Frame', tableWall: 'Echte tijd', tableVariable: 'Variabele positie', tableFixed: 'Vaste positie', tableDelta: 'Verschil', modelNote: 'Het variabele model gebruikt de huidige frameduur eenmaal met de snelheid. Het vaste model verzamelt alle echte tijd en beweegt in gelijke stappen. Geen van beide paden is een prestatiemeting.', privacyDisclosure: 'Je waarden worden alleen in deze browser opgeslagen, zodat het experiment klaarstaat wanneer je terugkomt. Er worden geen gamegegevens of telemetrie verzonden.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'eenheden', statusReady: 'Experiment bijgewerkt' },
  seo: [
    { type: 'title', level: 2, text: 'Begrijp de klok in een game-lus' },
    { type: 'paragraph', html: 'Elk gerenderd frame geeft de game nieuwe verstreken tijd. In een lus met variabele delta wordt beweging vaak bijgewerkt als <code>position += velocity × frameTime</code>. Bij stabiele frames blijft de gemiddelde snelheid dicht bij de bedoeling, maar één update kan zo groot worden als het frame dat haar veroorzaakte. Een hitch is daarom niet alleen een visuele pauze: hij verandert de hoeveelheid gametijd die die update verbruikt.' },
    { type: 'title', level: 2, text: 'Vergelijk variabele integratie met een vaste accumulator' },
    { type: 'paragraph', html: 'Een lus met vaste timestep telt elke frameduur op bij een accumulator en verbruikt daarna herhaaldelijk een gekozen stap zoals <code>16,667 ms</code>. De simulatie ziet gelijke updates, terwijl de renderer een ander ritme kan houden. De resterende fractie blijft in de accumulator voor het volgende frame. Bij een lang frame voert de vaste lus meerdere kleine updates uit om de verstreken tijd te verwerken. De stapgrootte blijft stabiel, maar er kan een inhaalpiek ontstaan.' },
    { type: 'table', headers: ['Situatie', 'Pad met variabele delta', 'Pad met vaste timestep', 'Beslissing om te overwegen'], rows: [['Stabiele rendering', 'Eén update gebruikt elke normale frameduur', 'Gelijke stappen verbruiken de verzamelde tijd', 'Beide paden zouden dezelfde beweging moeten volgen.'], ['Lang frame', 'Eén grote update kan een object te ver verplaatsen', 'Meerdere vaste updates halen de tijd in', 'Lees drift samen met het aantal inhaalstappen.'], ['Andere renderfrequentie', 'De updategrootte verandert met de framerate', 'De simulatiestap blijft gelijk', 'Vaste stappen verminderen renderafhankelijkheid.'], ['Delta-plafond', 'Tijd boven de grens wordt genegeerd', 'De accumulator ontvangt de volledige frameduur', 'Begrens alleen wanneer tijd verliezen aanvaardbaar is.']] },
    { type: 'title', level: 2, text: 'Zie wat een framepiek werkelijk doet' },
    { type: 'paragraph', html: 'Bij 60 frames per seconde duurt een normaal frame ongeveer <code>16,667 ms</code>. Met een extra piek van <code>80 ms</code> duurt één frame ongeveer <code>96,667 ms</code>. Het variabele model verwerkt die hele duur in één update. Het vaste model verwerkt in plaats daarvan ongeveer zes stappen van <code>16,667 ms</code>. De totale verstreken tijd kan gelijk zijn, terwijl het pad door de simulatie verschilt.' },
    { type: 'title', level: 2, text: 'Lees positiedrift samen met inhalen' },
    { type: 'paragraph', html: 'Positieverschil is het variabele pad min het vaste pad. Het toont hoe ver de twee integratiekeuzes uit elkaar zijn geraakt, niet automatisch welke keuze juist is. Het aantal inhaalstappen toont hoeveel vaste arbeid in één gerenderd frame nodig was. Een groot verschil wijst op zichtbare bewegingsafwijking; veel inhaalstappen wijzen op een mogelijk CPU-budgetprobleem. De signalen hangen samen, maar zijn niet dezelfde diagnose.' },
    { type: 'title', level: 2, text: 'Behandel delta begrenzen als een beleid' },
    { type: 'paragraph', html: 'Een begrenzing kan voorkomen dat een gepauzeerd tabblad, breakpoint of zware hitch een personage teleporteert of een physics-object door geometrie laat gaan. De prijs is dat de variabele klok achterloopt op de echte verstreken tijd. Als de game timing moet behouden, gebruik dan een vaste accumulator of ander herstelbeleid. Als sprongen begrensd en de game responsief moet blijven, kan een begrenzing passend zijn, maar het verlies aan tijd moet opzettelijk zijn.' },
    { type: 'title', level: 2, text: 'Kies de lus voor de taak die ze beschermt' },
    { type: 'table', headers: ['Taak in de game-lus', 'Nuttige standaard', 'Reden'], rows: [['Physics, botsingen of deterministische gameplay', 'Vaste timestep', 'Gelijke stappen maken de simulatie minder afhankelijk van het render-ritme.'], ['Eenvoudige visuele beweging zonder opgebouwde toestand', 'Variabele delta', 'De update is klein en heeft meestal geen inhaalwachtrij nodig.'], ['Gameplay-simulatie met vloeiende rendering', 'Vaste update met interpolatie', 'De simulatie houdt zijn stap terwijl de presentatie de fractie verbergt.'], ['Herstel na een zware stilstand', 'Begrensd inhaalbeleid', 'Voorkom dat één slecht frame onbeperkt simulatiewerk veroorzaakt.']] },
    { type: 'title', level: 2, text: 'Gebruik een herhaalbare afstelmethode' },
    { type: 'paragraph', html: 'Begin zonder pieken en bevestig dat beide paden samenvallen. Voeg één herhaalbare hitch toe en verander daarna het interval om te zien of de zichtbare fout optelt of stabiliseert. Pas de vaste stap aan en bekijk het aantal inhaalstappen voordat je de snelheid verandert. Schakel ten slotte de begrenzing in en vergelijk variabele simulatietijd met echte tijd. Zo scheid je de oorzaak van drift van het beleid dat haar moet beperken.' },
    { type: 'tip', title: 'Wat dit experiment niet kan bewijzen', html: 'Het laboratorium gebruikt opgegeven frameduren en constante snelheid. Het verklaart timinggedrag, maar meet geen apparaat en valideert geen engine. Echte physics, inputmeting, netwerk, interpolatie en framebudget kunnen de beste keuze veranderen. Gebruik het resultaat als hypothese en controleer die daarna in de echte game.' },
  ],
  faq, bibliographyTitle: 'Referenties over game-lussen', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
