import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Co pokazuje laboratorium stałego kroku czasu?', answer: 'Uruchamia ten sam poruszający się obiekt w pętli ze zmiennym delta time oraz w akumulatorze ze stałym timestepem. Powtarzalne skoki klatki pokazują czas symulacji, różnicę pozycji i kroki nadrabiania bez uruchamiania silnika gry.' },
  { question: 'Czym różni się zmienne delta od stałego timestepu?', answer: 'Model zmienny wykonuje krok raz na każdą wyrenderowaną klatkę i używa jej długości. Model stały działa w równych krokach symulacji, a akumulator przetwarza tyle kroków, ile wymaga upływ czasu rzeczywistego. Stałe kroki ograniczają zależność od częstotliwości renderowania, ale długa klatka może wymagać dodatkowej pracy.' },
  { question: 'Co oznacza wartość skoku klatki?', answer: 'Dodaje dodatkowe milisekundy do każdej wybranej klatki ze skokiem. Pole częstotliwości określa, co ile klatek pojawia się skok, więc można stworzyć powtarzalny hitch zamiast polegać na losowym pomiarze.' },
  { question: 'Co zmienia ograniczenie delta?', answer: 'Ograniczenie zmniejsza delta używane przez model zmienny, gdy klatka przekracza wybrany próg. Może zapobiec zbyt dużemu skokowi, ale zegar symulacji tego modelu pozostaje wtedy za czasem rzeczywistym. Stały akumulator nadal uwzględnia całą długość klatki.' },
  { question: 'Czy to profiler albo zamiennik testów gry?', answer: 'Nie. To deterministyczne laboratorium edukacyjne i projektowe korzystające z zadanych liczb. Nie mierzy urządzenia, nie diagnozuje silnika, nie modeluje kosztu renderowania i nie dowodzi, że jedna pętla pasuje do każdej gry.' },
];
const howTo = [
  { name: 'Wybierz rytm klatek', text: 'Ustaw docelową liczbę klatek na sekundę i dodaj powtarzalny skok w milisekundach. Częstotliwość umieszcza go co wybraną liczbę klatek.' },
  { name: 'Ustaw krok symulacji', text: 'Wybierz stały timestep w milisekundach. Wartość bliska 16,667 milisekundy oznacza około 60 aktualizacji symulacji na sekundę.' },
  { name: 'Nadaj obu światom tę samą regułę ruchu', text: 'Ustaw prędkość i czas trwania. Oba modele poruszają ten sam obiekt, więc różnica pozycji wynika ze sposobu wykorzystania upływającego czasu.' },
  { name: 'Świadomie przetestuj ograniczenie', text: 'Włącz ograniczenie delta i porównaj czas symulacji modelu zmiennego ze stałym akumulatorem. Ograniczenie to decyzja z widocznym kosztem, a nie darmowa poprawka.' },
  { name: 'Odczytaj dowody', text: 'Sprawdź obie ścieżki, podsumowanie rozbieżności, oś czasu, nadrabianie oraz dostępną tabelę klatek. Podczas nauki lub debugowania zmieniaj jedną wartość naraz.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratorium game delta time i stałego timestepu', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Porównać zmienne delta time ze stałym timestepem', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorium-delta-time-i-stalego-timestepu-gier', title: 'Laboratorium Delta Time i Stałego Timestepu Gier', description: 'Porównaj pętle gier ze zmiennym delta i stałym timestepem dzięki powtarzalnym skokom klatek, symulacji ruchu, krokom nadrabiania i widocznej różnicy czasu.',
  ui: { controlsTitle: 'Zbuduj wzorzec klatek', fpsLabel: 'Docelowa liczba klatek', fpsHint: 'Wyrenderowane klatki na sekundę', spikeLabel: 'Skok klatki', spikeHint: 'Dodatkowy czas dla klatek ze skokiem', spikeEveryLabel: 'Skok co ile klatek', fixedDtLabel: 'Stały timestep', fixedDtHint: 'Równa długość kroku symulacji', velocityLabel: 'Prędkość obiektu', durationLabel: 'Czas trwania', clampLabel: 'Limit delta', clampToggle: 'Ogranicz zmienne delta', runLabel: 'Uruchom eksperyment', resetLabel: 'Przywróć wartości', stageKicker: 'Pole doświadczalne', stageTitle: 'Dwa zegary, jeden poruszający się obiekt', stageCaption: 'Słupki pokazują hitches, linie śledzą obie pozycje, a dolna ścieżka izoluje różnicę ukrytą przez wartości końcowe.', frameTraceLabel: 'Długości klatek', positionPlotLabel: 'Pozycja obiektu', differencePlotLabel: 'Różnica pozycji względem stałej ścieżki', variableLane: 'Zmienna delta', fixedLane: 'Stały akumulator', frameCountLabel: 'Wyrenderowane klatki', wallTimeLabel: 'Czas rzeczywisty', variableTimeLabel: 'Zmienny czas symulacji', fixedTimeLabel: 'Stały czas symulacji', divergenceLabel: 'Różnica pozycji', stepsLabel: 'Stałe kroki symulacji', diagnosticsTitle: 'Odczyt klatek', stableStatus: 'Obie ścieżki pozostają zgodne dla tego wzorca.', variableStatus: 'Zmienna ścieżka wyprzedza, bo jej długości klatek zawierają skoki.', fixedStatus: 'Stała ścieżka nadrabia po długiej klatce kilkoma krokami symulacji.', clampStatus: 'Limit zmniejsza zmienny skok i pozostawia ten model za upływającym czasem rzeczywistym.', timelineTitle: 'Rejestr ruchu', timelineCaption: 'Pozycja względem upływającego czasu rzeczywistego. Linia przerywana oznacza równe stałe kroki.', frameAxis: 'Upływający czas rzeczywisty', positionAxis: 'Pozycja obiektu', legendVariable: 'Ścieżka zmiennej delty', legendFixed: 'Ścieżka stałego timestepu', legendSpike: 'Skok klatki', tableTitle: 'Dostępny rejestr klatek', tableFrame: 'Klatka', tableWall: 'Czas rzeczywisty', tableVariable: 'Pozycja zmienna', tableFixed: 'Pozycja stała', tableDelta: 'Różnica', modelNote: 'Model zmienny stosuje prędkość raz z bieżącą długością klatki. Model stały gromadzi cały czas rzeczywisty i porusza się równymi krokami. Żadna ścieżka nie jest pomiarem wydajności.', privacyDisclosure: 'Wartości są zapisywane tylko w tej przeglądarce, aby eksperyment był gotowy po powrocie. Żadne dane gry ani telemetria nie są wysyłane.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'jedn.', statusReady: 'Eksperyment zaktualizowany' },
  seo: [
    { type: 'title', level: 2, text: 'Zrozum zegar wewnątrz pętli gry' },
    { type: 'paragraph', html: 'Każda wyrenderowana klatka dostarcza grze nowy czas, który upłynął. W pętli ze zmiennym delta ruch jest często aktualizowany jako <code>position += velocity × frameTime</code>. Przy równych klatkach średnia prędkość pozostaje bliska zamierzonej, ale pojedyncza aktualizacja może być tak duża jak klatka, która ją wywołała. Hitch nie jest więc tylko pauzą obrazu: zmienia ilość czasu gry zużytą przez tę aktualizację.' },
    { type: 'title', level: 2, text: 'Porównaj zmienną integrację ze stałym akumulatorem' },
    { type: 'paragraph', html: 'Pętla ze stałym timestepem dodaje długość każdej klatki do akumulatora, a następnie wielokrotnie zużywa wybrany krok, na przykład <code>16,667 ms</code>. Symulacja dostaje równe aktualizacje, choć renderer może pracować w innym rytmie. Pozostały ułamek zostaje w akumulatorze na następną klatkę. Gdy pojawia się długa klatka, stała pętla wykonuje kilka małych aktualizacji, aby uwzględnić upływ czasu. Krok pozostaje stabilny, lecz może wystąpić skok pracy nadrabiania.' },
    { type: 'table', headers: ['Sytuacja', 'Ścieżka zmiennej delty', 'Ścieżka stałego timestepu', 'Decyzja do rozważenia'], rows: [['Stabilne renderowanie', 'Jedna aktualizacja używa każdej zwykłej długości klatki', 'Równe kroki zużywają zgromadzony czas', 'Obie ścieżki powinny podążać za tym samym ruchem.'], ['Długa klatka', 'Duża aktualizacja może przesunąć obiekt za daleko', 'Kilka stałych aktualizacji nadrabia czas', 'Odczytaj różnicę razem z liczbą kroków nadrabiania.'], ['Inna częstotliwość renderowania', 'Rozmiar aktualizacji zmienia się z frame rate', 'Krok symulacji pozostaje taki sam', 'Stałe kroki zmniejszają zależność od renderowania.'], ['Limit delta', 'Czas ponad limitem jest pomijany', 'Akumulator dostaje pełną długość klatki', 'Ograniczaj tylko wtedy, gdy utrata czasu jest akceptowalna.']] },
    { type: 'title', level: 2, text: 'Zobacz rzeczywisty skutek skoku klatki' },
    { type: 'paragraph', html: 'Przy 60 klatkach na sekundę zwykła klatka trwa około <code>16,667 ms</code>. Z dodatkowym skokiem <code>80 ms</code> jedna klatka trwa około <code>96,667 ms</code>. Model zmienny zużywa cały ten czas w jednej aktualizacji. Model stały zużywa zamiast tego około sześciu kroków po <code>16,667 ms</code>. Całkowity upływ czasu może być taki sam, choć droga przez symulację jest inna.' },
    { type: 'title', level: 2, text: 'Czytaj różnicę pozycji razem z nadrabianiem' },
    { type: 'paragraph', html: 'Różnica pozycji to ścieżka zmienna minus stała. Pokazuje, jak bardzo rozeszły się zasady integracji, ale nie mówi automatycznie, która jest poprawna. Liczba kroków nadrabiania pokazuje, ile stałej pracy wykonano w jednej wyrenderowanej klatce. Duża różnica wskazuje na widoczną rozbieżność ruchu; duża liczba kroków wskazuje na możliwy problem budżetu CPU. Sygnały są powiązane, lecz nie oznaczają tej samej diagnozy.' },
    { type: 'title', level: 2, text: 'Traktuj ograniczenie delta jak politykę' },
    { type: 'paragraph', html: 'Limit może zapobiec teleportacji postaci albo przenikaniu ciała fizycznego przez geometrię po wstrzymaniu karty, breakpointcie lub silnym hitchu. Ceną jest opóźnienie zmiennego zegara względem rzeczywistego czasu. Jeśli gra musi zachować czas, użyj stałego akumulatora albo innej polityki odzyskiwania. Jeśli musi ograniczać skoki i pozostać responsywna, limit może pasować, ale utracony czas powinien być zamierzony.' },
    { type: 'title', level: 2, text: 'Wybierz pętlę według zadania, które chroni' },
    { type: 'table', headers: ['Zadanie pętli gry', 'Przydatny wybór domyślny', 'Powód'], rows: [['Fizyka, kolizje lub deterministyczna rozgrywka', 'Stały timestep', 'Równe kroki ograniczają zależność symulacji od rytmu renderowania.'], ['Prosty ruch wizualny bez akumulowanego stanu', 'Zmienna delta', 'Aktualizacja jest mała i zwykle nie potrzebuje kolejki nadrabiania.'], ['Symulacja rozgrywki z płynnym renderingiem', 'Stała aktualizacja z interpolacją', 'Symulacja zachowuje krok, a prezentacja ukrywa ułamek postępu.'], ['Odzyskiwanie po poważnym zatrzymaniu', 'Ograniczona polityka nadrabiania', 'Jeden zły frame nie powinien tworzyć nieograniczonej pracy.']] },
    { type: 'title', level: 2, text: 'Zastosuj powtarzalny proces strojenia' },
    { type: 'paragraph', html: 'Zacznij bez skoków i potwierdź zgodność obu ścieżek. Dodaj powtarzalny hitch, a następnie zmień jego częstotliwość, aby sprawdzić, czy widoczny błąd narasta, czy się stabilizuje. Dostosuj stały krok i obserwuj liczbę kroków nadrabiania przed zmianą prędkości. Na końcu włącz limit i porównaj zmienny czas symulacji z czasem rzeczywistym. Ta kolejność oddziela przyczynę rozbieżności od polityki, która ma ją ograniczać.' },
    { type: 'tip', title: 'Czego ten eksperyment nie dowodzi', html: 'Laboratorium używa zadanych długości klatek i stałej prędkości, więc wyjaśnia zachowanie czasu, ale nie mierzy urządzenia i nie zatwierdza silnika. Rzeczywista fizyka, próbkowanie wejścia, sieć, interpolacja i budżet klatki mogą zmienić najlepszy projekt. Potraktuj wynik jako hipotezę i sprawdź ją w prawdziwej grze.' },
  ],
  faq, bibliographyTitle: 'Materiały o pętlach gry', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
