import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'O que este laboratório de timestep fixo demonstra?', answer: 'Ele executa o mesmo objeto em movimento em um loop de delta variável e em um acumulador de timestep fixo. Picos de frame repetíveis tornam visíveis o tempo simulado, o desvio de posição e os passos de recuperação sem executar uma engine de jogo.' },
  { question: 'Qual é a diferença entre delta variável e timestep fixo?', answer: 'O modelo variável avança uma vez por frame renderizado usando a duração desse frame. O modelo fixo avança em passos de simulação iguais e usa um acumulador para processar os passos exigidos pelo tempo real decorrido. Passos fixos reduzem a dependência da taxa de renderização, mas um frame longo pode exigir trabalho extra.' },
  { question: 'O que representa a entrada de pico de frame?', answer: 'Ela adiciona milissegundos extras a cada frame escolhido como pico. O campo de frequência define a cada quantos frames o pico aparece, permitindo criar um hitch repetível em vez de depender de uma captura aleatória.' },
  { question: 'O que muda ao limitar o delta?', answer: 'O limite reduz o delta usado pelo modelo variável quando um frame ultrapassa o teto escolhido. Isso pode impedir um salto grande, mas faz o relógio simulado desse modelo ficar atrasado em relação ao tempo real. O acumulador fixo continua contabilizando toda a duração do frame.' },
  { question: 'Isto é um profiler ou substitui os testes do jogo?', answer: 'Não. É um laboratório determinístico de aprendizagem e design com números declarados. Ele não mede o seu dispositivo, diagnostica uma engine, modela o custo de renderização nem prova que um loop seja correto para todos os jogos.' },
];
const howTo = [
  { name: 'Escolher o ritmo dos frames', text: 'Defina os frames por segundo desejados e adicione um pico repetível em milissegundos. Use a frequência para posicionar esse pico a cada determinado número de frames.' },
  { name: 'Definir o passo de simulação', text: 'Escolha o timestep fixo em milissegundos. Um valor próximo de 16,667 milissegundos representa cerca de 60 atualizações de simulação por segundo.' },
  { name: 'Dar a mesma regra de movimento', text: 'Defina velocidade e duração. Os dois modelos movem o mesmo objeto, então a diferença de posição vem da forma como cada um consome o tempo decorrido.' },
  { name: 'Testar um limite conscientemente', text: 'Ative o limite de delta e compare o tempo simulado do modelo variável com o acumulador fixo. Um limite é uma escolha com um custo visível, não uma correção gratuita.' },
  { name: 'Ler as evidências', text: 'Observe as duas trajetórias, o resumo da divergência, a linha do tempo, a recuperação e a tabela acessível de frames. Altere uma entrada por vez ao ensinar ou depurar o loop.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratório de delta time e timestep fixo para jogos', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Comparar delta time variável com timestep fixo', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorio-delta-time-e-timestep-fixo-jogos', title: 'Laboratório de Delta Time e Timestep Fixo para Jogos', description: 'Compare loops de jogo com delta variável e timestep fixo usando picos de frame repetíveis, movimento simulado, passos de recuperação e desvio temporal visível.',
  ui: { controlsTitle: 'Monte o padrão de frames', fpsLabel: 'Taxa de frames alvo', fpsHint: 'Frames renderizados por segundo', spikeLabel: 'Pico de frame', spikeHint: 'Tempo extra adicionado aos frames de pico', spikeEveryLabel: 'Pico a cada frames', fixedDtLabel: 'Timestep fixo', fixedDtHint: 'Tamanho igual do passo de simulação', velocityLabel: 'Velocidade do objeto', durationLabel: 'Duração do experimento', clampLabel: 'Teto do delta', clampToggle: 'Limitar o delta variável', runLabel: 'Executar experimento', resetLabel: 'Redefinir valores', stageKicker: 'O campo de testes', stageTitle: 'Dois relógios, um objeto em movimento', stageCaption: 'As barras mostram os hitches, as linhas acompanham as duas posições e o traço inferior isola o desvio que os valores finais podem esconder.', frameTraceLabel: 'Durações dos frames', positionPlotLabel: 'Posição do objeto', differencePlotLabel: 'Diferença de posição em relação ao caminho fixo', variableLane: 'Delta variável', fixedLane: 'Acumulador fixo', frameCountLabel: 'Frames renderizados', wallTimeLabel: 'Tempo real', variableTimeLabel: 'Tempo simulado variável', fixedTimeLabel: 'Tempo simulado fixo', divergenceLabel: 'Diferença de posição', stepsLabel: 'Passos de simulação fixos', diagnosticsTitle: 'Leitura dos frames', stableStatus: 'Os dois caminhos permanecem alinhados neste padrão.', variableStatus: 'O caminho variável avança porque as suas durações incluem os picos.', fixedStatus: 'O caminho fixo recupera o tempo com vários passos de simulação depois de um frame longo.', clampStatus: 'O limite reduz o salto variável e deixa esse modelo atrás do tempo real decorrido.', timelineTitle: 'O registro do movimento', timelineCaption: 'Posição ao longo do tempo real decorrido. Uma linha tracejada marca passos fixos iguais.', frameAxis: 'Tempo real decorrido', positionAxis: 'Posição do objeto', legendVariable: 'Caminho de delta variável', legendFixed: 'Caminho de timestep fixo', legendSpike: 'Pico de frame', tableTitle: 'Registro acessível de frames', tableFrame: 'Frame', tableWall: 'Tempo real', tableVariable: 'Posição variável', tableFixed: 'Posição fixa', tableDelta: 'Diferença', modelNote: 'O modelo variável aplica a velocidade uma vez com a duração do frame atual. O modelo fixo acumula todo o tempo real e avança em passos iguais. Nenhum caminho é uma medição de desempenho.', privacyDisclosure: 'Os seus valores são guardados apenas neste navegador para que o experimento esteja pronto quando voltar. Nenhum dado do jogo ou telemetria é enviado.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'unidades', statusReady: 'Experimento atualizado' },
  seo: [
    { type: 'title', level: 2, text: 'Entenda o relógio dentro de um loop de jogo' },
    { type: 'paragraph', html: 'Cada frame renderizado entrega ao jogo um novo tempo decorrido. Em um loop de delta variável, o movimento costuma ser atualizado como <code>position += velocity × frameTime</code>. Quando os frames são estáveis, a velocidade média fica próxima da desejada, mas uma atualização pode ter o mesmo tamanho do frame que a produziu. Por isso, um hitch não é apenas uma pausa visual: ele muda a quantidade de tempo de jogo consumida por essa atualização.' },
    { type: 'title', level: 2, text: 'Compare a integração variável com um acumulador fixo' },
    { type: 'paragraph', html: 'Um loop de timestep fixo soma a duração de cada frame a um acumulador e consome repetidamente um passo escolhido, como <code>16,667 ms</code>. A simulação recebe atualizações iguais enquanto o render pode manter outro ritmo. A fração restante fica no acumulador para o próximo frame. Quando chega um frame longo, o loop fixo executa várias atualizações pequenas para contabilizar o tempo decorrido. O tamanho do passo permanece estável, mas pode surgir um pico de trabalho de recuperação.' },
    { type: 'table', headers: ['Situação', 'Caminho de delta variável', 'Caminho de timestep fixo', 'Decisão a considerar'], rows: [['Renderização estável', 'Uma atualização usa cada duração normal', 'Passos iguais consomem o tempo acumulado', 'Os dois caminhos devem acompanhar o mesmo movimento.'], ['Frame longo', 'Uma atualização grande pode mover o objeto longe demais', 'Várias atualizações fixas recuperam o tempo', 'Observe o desvio junto com a contagem de recuperação.'], ['Taxa de renderização diferente', 'O tamanho da atualização muda com o frame rate', 'O passo de simulação permanece igual', 'Passos fixos reduzem a dependência do render.'], ['Teto do delta', 'O tempo acima do limite é ignorado', 'O acumulador recebe a duração completa', 'Limite apenas quando perder tempo for aceitável.']] },
    { type: 'title', level: 2, text: 'Veja o que um pico de frame realmente faz' },
    { type: 'paragraph', html: 'A 60 frames por segundo, um frame normal dura cerca de <code>16,667 ms</code>. Com um pico adicional de <code>80 ms</code>, um frame passa a durar cerca de <code>96,667 ms</code>. O modelo variável consome toda essa duração em uma atualização. O modelo fixo consome em vez disso cerca de seis passos de <code>16,667 ms</code>. O tempo total decorrido pode coincidir, embora o percurso dentro da simulação seja diferente.' },
    { type: 'title', level: 2, text: 'Leia o desvio de posição junto com a recuperação' },
    { type: 'paragraph', html: 'A diferença de posição é o caminho variável menos o caminho fixo. Ela mostra o quanto as duas políticas de integração se separaram, não qual delas está automaticamente correta. A contagem de recuperação mostra quanto trabalho fixo foi necessário em um único frame renderizado. Uma diferença grande aponta para uma divergência de movimento visível; muitos passos apontam para um possível problema de orçamento de CPU. Os sinais estão relacionados, mas não dão o mesmo diagnóstico.' },
    { type: 'title', level: 2, text: 'Trate o limite do delta como uma política' },
    { type: 'paragraph', html: 'Um limite pode impedir que uma aba pausada, um breakpoint ou um hitch grave teletransporte um personagem ou faça um corpo físico atravessar a geometria. O custo é que o relógio variável fica atrás do tempo real decorrido. Se o jogo precisa preservar o tempo, use um acumulador fixo ou outra política de recuperação. Se precisa manter os saltos limitados e continuar responsivo, um limite pode ser adequado, mas o tempo perdido deve ser intencional.' },
    { type: 'title', level: 2, text: 'Escolha o loop pelo trabalho que ele protege' },
    { type: 'table', headers: ['Trabalho do loop', 'Padrão útil', 'Motivo'], rows: [['Física, colisões ou gameplay determinístico', 'Timestep fixo', 'Passos iguais tornam a simulação menos dependente do ritmo de renderização.'], ['Movimento visual simples sem estado acumulado', 'Delta variável', 'A atualização é pequena e normalmente não precisa de uma fila de recuperação.'], ['Simulação de gameplay com renderização suave', 'Atualização fixa com interpolação', 'A simulação mantém o passo enquanto a apresentação esconde o progresso fracionário.'], ['Recuperação depois de uma pausa grave', 'Política de recuperação limitada', 'Evita transformar um frame ruim em trabalho de simulação ilimitado.']] },
    { type: 'title', level: 2, text: 'Use um fluxo de ajuste repetível' },
    { type: 'paragraph', html: 'Comece sem picos e confirme que os dois caminhos coincidem. Adicione um hitch repetível e mude a sua frequência para ver se o erro visível se acumula ou se estabiliza. Ajuste o passo fixo e observe a contagem de recuperação antes de alterar a velocidade. Por fim, ative o limite e compare o tempo simulado variável com o tempo real. Essa sequência separa a causa de uma divergência da política usada para contê-la.' },
    { type: 'tip', title: 'O que este experimento não pode provar', html: 'O laboratório usa durações de frame declaradas e velocidade constante, portanto explica o comportamento temporal, mas não mede um dispositivo nem valida uma engine. Física real, amostragem de entrada, rede, interpolação e orçamento de frame podem mudar o melhor design. Use o resultado para formular uma hipótese e depois verifique-a no jogo real.' },
  ],
  faq, bibliographyTitle: 'Referências sobre loops de jogos', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
