import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Vad visar det här laboratoriet för fast timestep?', answer: 'Det kör samma rörliga objekt genom en loop med variabel delta-tid och en ackumulator med fast timestep. Upprepningsbara bildrute-spikar gör simulerad tid, positionsdrift och ikappsteg synliga utan att starta en spelmotor.' },
  { question: 'Vad är skillnaden mellan variabel delta och fast timestep?', answer: 'Den variabla modellen uppdateras en gång per renderad bildruta och använder bildrutans längd. Den fasta modellen använder lika stora simuleringssteg och en ackumulator som behandlar så många steg som den förflutna verkliga tiden kräver. Fasta steg minskar beroendet av renderingsfrekvensen, men en lång bildruta kan skapa extra ikapparbete.' },
  { question: 'Vad betyder inmatningen för en bildrute-spik?', answer: 'Den lägger till extra millisekunder på varje vald spikbildruta. Fältet för intervall bestämmer efter hur många bildrutor spiken kommer, så du kan skapa ett upprepningsbart hitchmönster.' },
  { question: 'Vad ändras när delta begränsas?', answer: 'Gränsen minskar den delta som den variabla modellen använder när en bildruta är längre än det valda taket. Det kan förhindra ett för stort hopp, men modellens simulerade klocka hamnar efter verklig tid. Den fasta ackumulatorn räknar fortfarande hela bildrutans längd.' },
  { question: 'Är detta en profiler eller ersätter det speltestning?', answer: 'Nej. Det är ett deterministiskt laboratorium för lärande och design med angivna tal. Det mäter inte en enhet, diagnostiserar ingen motor, modellerar inte renderingskostnad och bevisar inte att en loop passar alla spel.' },
];
const howTo = [
  { name: 'Välj bildrutornas rytm', text: 'Ställ in önskat antal bildrutor per sekund och lägg till en upprepningsbar spik i millisekunder. Intervallet placerar spiken med det valda antalet bildrutor emellan.' },
  { name: 'Ställ in simuleringssteget', text: 'Välj fast timestep i millisekunder. Ett värde nära 16,667 millisekunder motsvarar ungefär 60 simuleringsuppdateringar per sekund.' },
  { name: 'Ge båda modellerna samma rörelseregel', text: 'Ange hastighet och varaktighet. Båda modellerna flyttar samma objekt, så positionsskillnaden beror på hur de använder den förflutna tiden.' },
  { name: 'Testa en gräns medvetet', text: 'Aktivera delta-gränsen och jämför variabel simulerad tid med den fasta ackumulatorn. En gräns är ett val med synlig kostnad, inte en gratis korrigering.' },
  { name: 'Läs bevisen', text: 'Granska de två banorna, sammanfattningen av avvikelsen, tidslinjen, ikappbeteendet och den tillgängliga bildrutetabellen. Ändra en inmatning i taget när du lär ut eller felsöker loopen.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Laboratorium för game delta-tid och fast timestep', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Jämför variabel delta-tid med fast timestep', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'laboratorium-game-delta-tid-och-fast-timestep', title: 'Laboratorium för Game Delta tid och Fast Timestep', description: 'Jämför spel-loopar med variabel delta och fast timestep med upprepningsbara bildrute-spikar, simulerad rörelse, ikappsteg och synlig tidsdrift.',
  ui: { controlsTitle: 'Bygg bildrutemönstret', fpsLabel: 'Målfrekvens', fpsHint: 'Renderade bildrutor per sekund', spikeLabel: 'Bildrute-spik', spikeHint: 'Extra tid på spikbildrutor', spikeEveryLabel: 'Spik var n:te bildruta', fixedDtLabel: 'Fast timestep', fixedDtHint: 'Lika stort simuleringssteg', velocityLabel: 'Objektets hastighet', durationLabel: 'Körningens längd', clampLabel: 'Delta-tak', clampToggle: 'Begränsa variabel delta-tid', runLabel: 'Kör experiment', resetLabel: 'Återställ värden', stageKicker: 'Testfältet', stageTitle: 'Två klockor, ett rörligt objekt', stageCaption: 'Staplarna visar hitchar, linjerna följer båda positionerna och det nedre spåret isolerar driften som slutvärden kan dölja.', frameTraceLabel: 'Bildrutors längd', positionPlotLabel: 'Objektets position', differencePlotLabel: 'Positionsskillnad från fast bana', variableLane: 'Variabel delta', fixedLane: 'Fast ackumulator', frameCountLabel: 'Renderade bildrutor', wallTimeLabel: 'Verklig tid', variableTimeLabel: 'Variabel simulerad tid', fixedTimeLabel: 'Fast simulerad tid', divergenceLabel: 'Positionsskillnad', stepsLabel: 'Fasta simuleringssteg', diagnosticsTitle: 'Bildruteläsning', stableStatus: 'De två banorna förblir samordnade för detta mönster.', variableStatus: 'Den variabla banan går före eftersom bildrutornas längder innehåller spikarna.', fixedStatus: 'Den fasta banan kommer ikapp med flera simuleringssteg efter en lång bildruta.', clampStatus: 'Gränsen minskar det variabla hoppet och lämnar modellen efter den förflutna verkliga tiden.', timelineTitle: 'Rörelseloggen', timelineCaption: 'Position över förfluten verklig tid. En streckad linje markerar lika fasta steg.', frameAxis: 'Förfluten verklig tid', positionAxis: 'Objektets position', legendVariable: 'Variabel delta-bana', legendFixed: 'Fast timestep-bana', legendSpike: 'Bildrute-spik', tableTitle: 'Tillgänglig bildruteloggen', tableFrame: 'Bildruta', tableWall: 'Verklig tid', tableVariable: 'Variabel position', tableFixed: 'Fast position', tableDelta: 'Skillnad', modelNote: 'Den variabla modellen använder aktuell bildrutelängd för att tillämpa hastigheten en gång. Den fasta modellen samlar all verklig tid och rör sig i lika steg. Ingen bana är en prestandamätning.', privacyDisclosure: 'Dina värden sparas bara i den här webbläsaren så att experimentet är redo när du återkommer. Inga speldata eller telemetri skickas.', unitMs: 'ms', unitSeconds: 's', unitPixels: 'enheter', statusReady: 'Experimentet uppdaterades' },
  seo: [
    { type: 'title', level: 2, text: 'Förstå klockan i en spel-loop' },
    { type: 'paragraph', html: 'Varje renderad bildruta ger spelet en ny förfluten tid. I en loop med variabel delta uppdateras rörelse ofta som <code>position += velocity × frameTime</code>. När bildrutorna är stabila ligger medelhastigheten nära den avsedda, men en enskild uppdatering kan bli lika stor som bildrutan som skapade den. En hitch är därför inte bara en visuell paus: den ändrar hur mycket speltid uppdateringen förbrukar.' },
    { type: 'title', level: 2, text: 'Jämför variabel integration med en fast ackumulator' },
    { type: 'paragraph', html: 'En loop med fast timestep lägger varje bildrutelängd i en ackumulator och förbrukar sedan upprepade gånger ett valt steg som <code>16,667 ms</code>. Simuleringen får lika stora uppdateringar medan renderingen kan hålla en annan rytm. Den återstående bråkdelen ligger kvar till nästa bildruta. När en lång bildruta kommer utför den fasta loopen flera små uppdateringar för att täcka den förflutna tiden. Steget förblir stabilt, men ikapparbetet kan ge en belastningstopp.' },
    { type: 'table', headers: ['Situation', 'Variabel delta-bana', 'Fast timestep-bana', 'Beslut att överväga'], rows: [['Stabil rendering', 'En uppdatering använder varje normal bildrutelängd', 'Lika steg förbrukar den ackumulerade tiden', 'Båda bör följa samma rörelse nära.'], ['Lång bildruta', 'En stor uppdatering kan flytta objektet för långt', 'Flera fasta uppdateringar kommer ikapp tiden', 'Läs drift och antal ikappsteg tillsammans.'], ['Annan renderingsfrekvens', 'Uppdateringens storlek ändras med frekvensen', 'Simuleringssteget förblir samma', 'Fasta steg minskar beroendet av rendering.'], ['Delta-tak', 'Tid över taket ignoreras', 'Ackumulatorn får hela bildrutans längd', 'Begränsa bara när förlorad tid är acceptabel.']] },
    { type: 'title', level: 2, text: 'Se vad en bildrute-spik faktiskt gör' },
    { type: 'paragraph', html: 'Vid 60 bildrutor per sekund tar en normal bildruta ungefär <code>16,667 ms</code>. Med en extra spik på <code>80 ms</code> blir en bildruta ungefär <code>96,667 ms</code>. Den variabla modellen förbrukar hela längden i en uppdatering. Den fasta modellen förbrukar i stället ungefär sex steg på <code>16,667 ms</code>. Den totala förflutna tiden kan stämma, även om vägen genom simuleringen skiljer sig.' },
    { type: 'title', level: 2, text: 'Läs positionsdrift och ikappsteg tillsammans' },
    { type: 'paragraph', html: 'Positionsskillnaden är den variabla banan minus den fasta banan. Den visar hur långt de två integrationsreglerna har separerat, inte vilken som automatiskt är rätt. Antalet ikappsteg visar hur mycket fast arbete som krävdes i en enda renderad bildruta. En stor skillnad pekar på synlig rörelseavvikelse; många ikappsteg pekar på ett möjligt CPU-budgetproblem. Signalerna hänger ihop, men är inte samma diagnos.' },
    { type: 'title', level: 2, text: 'Behandla delta-begränsning som en policy' },
    { type: 'paragraph', html: 'En gräns kan hindra en pausad flik, breakpoint eller allvarlig hitch från att teleportera en figur eller skicka en fysikkropp genom geometri. Priset är att den variabla klockan hamnar efter verkligt förfluten tid. Om spelet måste bevara tid bör du använda en fast ackumulator eller en annan återhämtningspolicy. Om spelet måste begränsa hopp och förbli responsivt kan en gräns fungera, men den förlorade tiden ska vara avsiktlig.' },
    { type: 'title', level: 2, text: 'Välj loopen efter arbetet den skyddar' },
    { type: 'table', headers: ['Arbete i spel-loopen', 'Användbar standard', 'Varför'], rows: [['Fysik, kollisioner eller deterministiskt gameplay', 'Fast timestep', 'Lika steg gör simuleringen mindre beroende av renderingsrytmen.'], ['Enkel visuell rörelse utan ackumulerat tillstånd', 'Variabel delta', 'Uppdateringen är liten och behöver oftast ingen ikappkö.'], ['Gameplay-simulering med mjuk rendering', 'Fast uppdatering med interpolation', 'Simuleringen behåller steget medan presentationen döljer bråkdelen.'], ['Återhämtning efter ett kraftigt stopp', 'Begränsad ikappolicy', 'Ett dåligt frame ska inte skapa obegränsat simuleringsarbete.']] },
    { type: 'title', level: 2, text: 'Följ ett upprepningsbart justeringsflöde' },
    { type: 'paragraph', html: 'Börja utan spikar och kontrollera att banorna sammanfaller. Lägg till en upprepningsbar hitch och ändra sedan intervallet för att se om det synliga felet växer eller stabiliseras. Justera det fasta steget och kontrollera antalet ikappsteg innan du ändrar hastigheten. Aktivera till sist gränsen och jämför variabel simulerad tid med verklig tid. Ordningen skiljer orsaken till drift från policyn som ska begränsa den.' },
    { type: 'tip', title: 'Vad experimentet inte kan bevisa', html: 'Laboratoriet använder angivna bildrutelängder och konstant hastighet. Det förklarar tidsbeteende, men mäter ingen enhet och validerar ingen motor. Verklig fysik, inmatningssampling, nätverk, interpolation och bildrutebudget kan ändra bästa design. Använd resultatet som en hypotes och kontrollera den i det faktiska spelet.' },
  ],
  faq, bibliographyTitle: 'Referenser om spel-loopar', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
