import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GameDeltaTimeFixedTimestepLabUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Bu sabit timestep laboratuvarı neyi gösterir?', answer: 'Aynı hareketli nesneyi değişken delta time döngüsünden ve sabit timestep akümülatöründen geçirir. Tekrarlanabilir frame sıçramaları, bir oyun motoru çalıştırmadan simülasyon zamanını, konum farkını ve yetişme adımlarını görünür kılar.' },
  { question: 'Değişken delta ile sabit timestep arasındaki fark nedir?', answer: 'Değişken model, oluşturulan her frame için frame süresini kullanarak bir kez ilerler. Sabit model eşit simülasyon adımlarıyla ilerler ve geçen gerçek zamanın gerektirdiği kadar adımı bir akümülatör üzerinden işler. Sabit adımlar render hızına bağımlılığı azaltır, ancak uzun bir frame ek yetişme işi oluşturabilir.' },
  { question: 'Frame sıçraması girdisi neyi temsil eder?', answer: 'Seçilen her sıçrama frame ine eklenecek milisaniyeleri temsil eder. Sıklık alanı sıçramanın kaç frame de bir görüleceğini belirler, böylece rastgele bir performans kaydı yerine tekrarlanabilir bir hitch deseni oluşturabilirsiniz.' },
  { question: 'Delta sınırı neyi değiştirir?', answer: 'Bir frame seçilen tavanı aştığında değişken modelin kullandığı delta yı sınırlar. Bu, aşırı büyük bir sıçramayı önleyebilir, fakat bu modelin simülasyon saati gerçek zamanın gerisinde kalır. Sabit akümülatör frame in tamamını hesaplamaya devam eder.' },
  { question: 'Bu bir profiler mı, oyun testinin yerini tutar mı?', answer: 'Hayır. Belirlenmiş sayılarla çalışan deterministik bir öğrenme ve tasarım laboratuvarıdır. Cihazınızı ölçmez, bir motoru teşhis etmez, render maliyetini modellemez ve tek bir döngünün her oyun için doğru olduğunu kanıtlamaz.' },
];
const howTo = [
  { name: 'Frame ritmini seçin', text: 'Hedef saniyedeki frame sayısını ayarlayın ve milisaniye cinsinden tekrarlanabilir bir sıçrama ekleyin. Sıklık alanı sıçramayı seçilen frame aralığına yerleştirir.' },
  { name: 'Simülasyon adımını ayarlayın', text: 'Sabit timestep değerini milisaniye cinsinden seçin. 16,667 milisaniyeye yakın bir değer saniyede yaklaşık 60 simülasyon güncellemesini temsil eder.' },
  { name: 'İki modele aynı hareket kuralını verin', text: 'Hızı ve süreyi belirleyin. İki model de aynı nesneyi hareket ettirdiği için konum farkı geçen zamanı tüketme biçimlerinden doğar.' },
  { name: 'Bir sınırı bilinçli şekilde test edin', text: 'Delta sınırını açın ve değişken simülasyon zamanını sabit akümülatörle karşılaştırın. Sınır, maliyeti görünen bir politika tercihidir; ücretsiz bir düzeltme değildir.' },
  { name: 'Kanıtı okuyun', text: 'İki yolu, fark özetini, zaman çizelgesini, yetişme davranışını ve erişilebilir frame tablosunu inceleyin. Öğretirken veya hata ayıklarken her seferinde tek bir girdiyi değiştirin.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Oyun delta time ve sabit timestep laboratuvarı', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Değişken delta time ile sabit timestep i karşılaştırma', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GameDeltaTimeFixedTimestepLabUI> = {
  slug: 'oyun-delta-time-ve-sabit-timestep-laboratuvari', title: 'Oyun Delta Time ve Sabit Timestep Laboratuvarı', description: 'Tekrarlanabilir frame sıçramaları, simüle hareket, yetişme adımları ve görünür zaman farkıyla değişken ve sabit oyun döngülerini karşılaştırın.',
  ui: { controlsTitle: 'Frame desenini oluşturun', fpsLabel: 'Hedef frame hızı', fpsHint: 'Saniyede oluşturulan frame', spikeLabel: 'Frame sıçraması', spikeHint: 'Sıçrama framelerine eklenen süre', spikeEveryLabel: 'Sıçrama aralığı', fixedDtLabel: 'Sabit timestep', fixedDtHint: 'Eşit simülasyon adımı boyutu', velocityLabel: 'Nesne hızı', durationLabel: 'Çalışma süresi', clampLabel: 'Delta tavanı', clampToggle: 'Değişken delta yı sınırla', runLabel: 'Deneyi çalıştır', resetLabel: 'Değerleri sıfırla', stageKicker: 'Deney alanı', stageTitle: 'İki saat, tek hareketli nesne', stageCaption: 'Çubuklar hitch leri, çizgiler iki konumu gösterir; alt iz, son değerlerin saklayabileceği farkı ayırır.', frameTraceLabel: 'Frame süreleri', positionPlotLabel: 'Nesne konumu', differencePlotLabel: 'Sabit yola göre konum farkı', variableLane: 'Değişken delta', fixedLane: 'Sabit akümülatör', frameCountLabel: 'Oluşturulan frame', wallTimeLabel: 'Gerçek zaman', variableTimeLabel: 'Değişken simülasyon zamanı', fixedTimeLabel: 'Sabit simülasyon zamanı', divergenceLabel: 'Konum farkı', stepsLabel: 'Sabit simülasyon adımları', diagnosticsTitle: 'Frame okuması', stableStatus: 'Bu desende iki yol hizalı kalıyor.', variableStatus: 'Frame süreleri sıçramaları içerdiği için değişken yol öne geçiyor.', fixedStatus: 'Uzun bir frame den sonra sabit yol birden fazla simülasyon adımıyla yetişiyor.', clampStatus: 'Sınır değişken sıçramayı azaltıyor ve bu modeli geçen gerçek zamanın gerisinde bırakıyor.', timelineTitle: 'Hareket kaydı', timelineCaption: 'Geçen gerçek zamana göre konum. Kesikli çizgi eşit sabit adımları gösterir.', frameAxis: 'Geçen gerçek zaman', positionAxis: 'Nesne konumu', legendVariable: 'Değişken delta yolu', legendFixed: 'Sabit timestep yolu', legendSpike: 'Frame sıçraması', tableTitle: 'Erişilebilir frame kaydı', tableFrame: 'Frame', tableWall: 'Gerçek zaman', tableVariable: 'Değişken konum', tableFixed: 'Sabit konum', tableDelta: 'Fark', modelNote: 'Değişken model, geçerli frame süresiyle hızı bir kez uygular. Sabit model tüm gerçek zamanı biriktirir ve eşit adımlarla ilerler. Hiçbir yol performans ölçümü değildir.', privacyDisclosure: 'Değerleriniz yalnızca bu tarayıcıda saklanır, böylece deney geri döndüğünüzde hazır olur. Oyun verisi veya telemetri gönderilmez.', unitMs: 'ms', unitSeconds: 'sn', unitPixels: 'birim', statusReady: 'Deney güncellendi' },
  seo: [
    { type: 'title', level: 2, text: 'Bir oyun döngüsündeki saati anlayın' },
    { type: 'paragraph', html: 'Oluşturulan her frame oyuna yeni bir geçen zaman değeri verir. Değişken delta döngüsünde hareket genellikle <code>position += velocity × frameTime</code> şeklinde güncellenir. Frame ler düzenliyken ortalama hız hedefe yakın kalır, ancak tek bir güncelleme onu üreten frame kadar büyük olabilir. Bu yüzden hitch yalnızca görsel bir duraklama değildir: o güncellemenin tükettiği oyun zamanını değiştirir.' },
    { type: 'title', level: 2, text: 'Değişken entegrasyonu sabit akümülatörle karşılaştırın' },
    { type: 'paragraph', html: 'Sabit timestep döngüsü her frame süresini bir akümülatöre ekler, ardından <code>16,667 ms</code> gibi seçilen bir adımı tekrar tekrar tüketir. Simülasyon eşit güncellemeler alırken renderer farklı bir ritimde çalışabilir. Kalan kesir bir sonraki frame için akümülatörde kalır. Uzun bir frame geldiğinde sabit döngü, geçen zamanı işlemek için birkaç küçük güncelleme yapar. Adım boyutu sabit kalır, ancak yetişme işi bir yük artışı oluşturabilir.' },
    { type: 'table', headers: ['Durum', 'Değişken delta yolu', 'Sabit timestep yolu', 'Düşünülecek karar'], rows: [['Düzenli render', 'Bir güncelleme her normal frame süresini kullanır', 'Eşit adımlar biriken zamanı tüketir', 'İki yolun aynı hareketi izlediğini kontrol edin.'], ['Uzun frame', 'Büyük bir güncelleme nesneyi fazla ileri taşıyabilir', 'Birden çok sabit güncelleme zamanı yakalar', 'Farkı yetişme adımı sayısıyla birlikte okuyun.'], ['Farklı render hızı', 'Güncelleme boyutu frame hızıyla değişir', 'Simülasyon adımı aynı kalır', 'Sabit adımlar render bağımlılığını azaltır.'], ['Delta tavanı', 'Tavanın üzerindeki zaman yok sayılır', 'Akümülatör frame in tamamını alır', 'Sadece zaman kaybı kabul edilebilirse sınır koyun.']] },
    { type: 'title', level: 2, text: 'Bir frame sıçramasının gerçek etkisini görün' },
    { type: 'paragraph', html: 'Saniyede 60 frame hızında normal bir frame yaklaşık <code>16,667 ms</code> sürer. Buna <code>80 ms</code> eklenirse tek bir frame yaklaşık <code>96,667 ms</code> olur. Değişken model bu sürenin tamamını tek güncellemede tüketir. Sabit model ise yaklaşık altı adet <code>16,667 ms</code> adımı tüketir. Toplam geçen zaman aynı olabilir, fakat simülasyondaki yol farklıdır.' },
    { type: 'title', level: 2, text: 'Konum farkını yetişme işiyle birlikte okuyun' },
    { type: 'paragraph', html: 'Konum farkı değişken yol eksi sabit yoldur. İki entegrasyon politikasının ne kadar ayrıldığını gösterir, ancak otomatik olarak hangisinin doğru olduğunu söylemez. Yetişme sayısı tek bir render frame inde gereken sabit iş miktarını gösterir. Büyük fark görünür hareket sapmasına, çok sayıda adım ise olası CPU bütçesi sorununa işaret eder. İlişkilidirler, fakat aynı teşhis değildir.' },
    { type: 'title', level: 2, text: 'Delta sınırlamasını bir politika olarak ele alın' },
    { type: 'paragraph', html: 'Sınır, duraklatılmış bir sekmenin, breakpoint in veya ağır bir hitch in karakteri ışınlamasını ya da fizik gövdesini geometriden geçirmesini önleyebilir. Bedeli, değişken saatin geçen gerçek zamanın gerisinde kalmasıdır. Oyun zamanı korumalıysa sabit akümülatör veya başka bir kurtarma politikası kullanın. Sıçramalar sınırlı ve oyun duyarlı kalmalıysa sınır uygun olabilir, ancak kaybedilen zaman bilinçli bir seçim olmalıdır.' },
    { type: 'title', level: 2, text: 'Döngüyü koruduğu işe göre seçin' },
    { type: 'table', headers: ['Oyun döngüsü işi', 'Yararlı varsayılan', 'Nedeni'], rows: [['Fizik, çarpışma veya deterministik oynanış', 'Sabit timestep', 'Eşit adımlar simülasyonu render ritmine daha az bağımlı kılar.'], ['Birikmiş durumu olmayan basit görsel hareket', 'Değişken delta', 'Güncelleme küçüktür ve genellikle yetişme kuyruğu gerekmez.'], ['Akıcı görüntülü oynanış simülasyonu', 'Enterpolasyonlu sabit güncelleme', 'Simülasyon adımını korur, gösterim ise kesirli ilerlemeyi gizler.'], ['Ciddi duraklama sonrası toparlanma', 'Sınırlı yetişme politikası', 'Kötü bir frame in sınırsız simülasyon işi üretmesini önler.']] },
    { type: 'title', level: 2, text: 'Tekrarlanabilir bir ayar akışı kullanın' },
    { type: 'paragraph', html: 'Sıçrama olmadan başlayın ve iki yolun aynı olduğunu doğrulayın. Tekrarlanabilir bir hitch ekleyin, ardından görünür hatanın birikip birikmediğini veya dengelenip dengelenmediğini görmek için sıklığını değiştirin. Hızı değiştirmeden önce sabit adımı ayarlayın ve yetişme sayısını inceleyin. Son olarak sınırı açın ve değişken simülasyon zamanını gerçek zamanla karşılaştırın. Bu sıra, farkın nedenini onu sınırlayan politikadan ayırır.' },
    { type: 'tip', title: 'Bu deney neyi kanıtlayamaz?', html: 'Laboratuvar belirlenmiş frame süreleri ve sabit hız kullanır; zaman davranışını açıklar ama bir cihazı ölçmez ve bir motoru doğrulamaz. Gerçek fizik, girdi örnekleme, ağ, enterpolasyon ve frame bütçesi en iyi tasarımı değiştirebilir. Sonucu bir hipotez olarak kullanın ve gerçek oyunda doğrulayın.' },
  ],
  faq, bibliographyTitle: 'Oyun döngüsü kaynakları', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
