import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Apa arti piksel per unit dalam game?', answer: 'Piksel per unit atau PPU menunjukkan jumlah piksel tekstur yang mewakili satu unit dunia. Kepadatan yang konsisten membuat sprite, tile, dan kamera memiliki skala yang mudah diprediksi.' },
  { question: 'Mengapa skala bilangan bulat penting?', answer: 'Skala bilangan bulat memberi setiap piksel sumber jumlah piksel layar yang sama. Skala pecahan dapat menghasilkan tepi yang tidak rata atau gambar buram.' },
  { question: 'Apa itu pixel bleeding?', answer: 'Pixel bleeding adalah warna yang tidak diinginkan dari texel tetangga atau area atlas lain. Filtering, tepi, gerakan subpiksel, dan padding yang kurang dapat menyebabkannya.' },
  { question: 'Bagaimana cara memakai skala yang direkomendasikan?', answer: 'Gunakan sebagai kandidat yang muat dalam resolusi dan dekat dengan target. Setelah itu periksa filtering nearest, posisi kamera, dan padding atlas di engine.' },
  { question: 'Apakah planner memilih PPU yang benar untuk setiap engine?', answer: 'Tidak. Ini adalah alat bantu aritmetika yang transparan. Kamera, import, mipmap, pembulatan, dan pixel snapping berbeda di setiap engine sehingga perlu diuji.' },
];
const howTo = [
  { name: 'Pilih layar tujuan', text: 'Masukkan lebar dan tinggi tampilan game atau resolusi referensi dalam piksel.' },
  { name: 'Muat sprite', text: 'Pilih gambar agar ukuran aslinya terdeteksi. Anda juga dapat memakai sprite contoh Bob.' },
  { name: 'Pilih skala', text: 'Gerakkan slider atau pilih preset. Pengali bilangan bulat adalah kandidat paling tajam.' },
  { name: 'Baca preview', text: 'Periksa footprint sprite, PPU horizontal dan vertikal, dunia yang terlihat, serta peringatan bleeding.' },
  { name: 'Uji di engine', text: 'Validasi pilihan dengan filtering nearest, kamera yang sejajar, padding atlas, dan resolusi game sebenarnya.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planner piksel per unit untuk game', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Menguji skala sprite pixel art', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'planner-piksel-per-unit-sprite-game', title: 'Planner piksel per unit untuk sprite game', description: 'Unggah sprite atau gunakan contoh Bob untuk melihat footprint pada berbagai skala bilangan bulat, membandingkan PPU, dan menemukan risiko pixel bleeding.',
  ui: {
    inputsTitle: 'Muat dan uji sprite Anda', uploadTitle: 'Gambar sumber Anda', uploadHint: 'Pilih PNG, GIF, WebP, atau JPEG. Ukuran asli gambar digunakan di setiap preview.', chooseSpriteLabel: 'Pilih sprite', noSpriteLabel: 'Belum ada sprite yang dimuat', defaultSpriteLabel: 'Sprite contoh Bob', loadedSpriteLabel: 'Dimuat', clearSpriteLabel: 'Hapus sprite', displayWidthLabel: 'Lebar layar px', displayHeightLabel: 'Tinggi layar px', spriteWidthLabel: 'Lebar sprite px', spriteHeightLabel: 'Tinggi sprite px', worldWidthLabel: 'Lebar sprite dalam unit', worldHeightLabel: 'Tinggi sprite dalam unit', targetScaleLabel: 'Skala target di layar', targetScaleHint: 'Piksel layar untuk setiap piksel tekstur.', resolutionPresetsLabel: 'Resolusi referensi', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Skala cepat', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Atur ulang nilai', fieldTitle: 'Lihat dalam beberapa ukuran', fieldCaption: 'Gambar yang dimuat dirender dengan skala nearest agar footprint sebenarnya dapat dinilai pada setiap pengali bilangan bulat.', previewPlaceholder: 'Muat sprite untuk memulai pengujian visual', previewScaleLabel: 'Skala preview', sourceImageAlt: 'Preview sprite yang dimuat', viewportLabel: 'Layar', spriteLabel: 'Sprite yang dirender', crispTitle: 'Skala tajam', crispCaption: 'Pengali bilangan bulat menjaga ukuran piksel tetap seragam. Langkah abu-abu melebihi layar yang dinyatakan.', fitLabel: 'Muat di layar:', yesLabel: 'ya', noLabel: 'tidak', recommendedLabel: 'paling mendekati', summaryTitle: 'Ringkasan rencana', ppuXLabel: 'PPU horizontal', ppuYLabel: 'PPU vertikal', viewportWorldLabel: 'Dunia terlihat', fitScaleLabel: 'Skala terbesar yang muat', bleedingRiskLabel: 'Risiko bleeding', lowRisk: 'Rendah', mediumRisk: 'Sedang', highRisk: 'Tinggi', riskLowMessage: 'Sumbu selaras dan skala target berupa bilangan bulat yang muat di layar. Tetap periksa filtering dan padding atlas.', riskMediumMessage: 'Target hanya cocok sebagian. Periksa perbedaan sumbu dan skala yang disorot.', riskHighMessage: 'Skala ini dapat membuat sampling tidak rata. Pilih pengali bilangan bulat dan periksa ukuran sprite.', alignmentLabel: 'Catatan sampling', tableTitle: 'Daftar skala yang mudah diakses', tableScale: 'Skala', tableWidth: 'Lebar render', tableHeight: 'Tinggi render', tableFits: 'Muat di layar', modelNote: 'PPU dihitung sebagai piksel sprite yang dirender dibagi ukuran sprite dalam unit pada setiap sumbu. Risiko bleeding adalah heuristik, bukan pemeriksaan tekstur atau jaminan engine.', privacyDisclosure: 'File diproses di browser ini. Sprite, file proyek, dan telemetri tidak dikirim.', statusReady: 'Preview diperbarui', unitPixels: 'px', unitUnits: 'unit',
  },
  seo: [
    { type: 'title', level: 2, text: 'Ubah ukuran sprite menjadi keputusan skala' }, { type: 'paragraph', html: 'Sprite memiliki ukuran bitmap dan ukuran yang ditempatinya di dunia game. PPU menghubungkan kedua ukuran tersebut. Preview menunjukkan akibat visualnya, bukan hanya angka abstrak.' }, { type: 'paragraph', html: 'Muat gambar nyata untuk memakai ukuran aslinya. Alat ini mengalikan setiap sumbu dengan skala pilihan lalu menghitung bagian dunia yang terlihat pada resolusi yang diberikan.' }, { type: 'title', level: 2, text: 'Hal yang perlu dilihat di preview' }, { type: 'list', items: ['Bandingkan footprint dengan layar referensi.', 'Uji skala bilangan bulat terlebih dahulu.', 'Gunakan kedua nilai PPU untuk menemukan peregangan yang tidak disengaja.', 'Anggap peringatan bleeding sebagai sinyal untuk menguji engine.'] }, { type: 'title', level: 2, text: 'Mengapa skala bilangan bulat lebih bersih' }, { type: 'paragraph', html: 'Pada 3x setiap piksel sumber menempati tiga piksel layar. Pada 2,5x renderer harus membagi lebar yang berbeda. Nearest mencegah pencampuran warna, tetapi tidak memperbaiki kamera di antara posisi piksel.' }, { type: 'table', headers: ['Sinyal', 'Makna', 'Keputusan berikutnya'], rows: [['PPU sama', 'Kedua sumbu memiliki kepadatan yang sama.', 'Bandingkan dengan tile dan grid proyek.'], ['Skala pecahan', 'Footprint tidak memakai bilangan bulat.', 'Coba skala bilangan bulat terdekat.'], ['Tidak muat', 'Sprite melampaui layar.', 'Kurangi skala atau tambah resolusi.']] }, { type: 'title', level: 2, text: 'Bedakan bleeding dari ukuran' }, { type: 'paragraph', html: 'Pixel bleeding biasanya berasal dari texel tetangga di atlas, filtering di tepi, atau koordinat kamera yang tidak sejajar. Untuk buram periksa filtering; untuk garis sambungan periksa padding dan batas atlas.' }, { type: 'title', level: 2, text: 'Pelajari alur dengan sprite Bob' }, { type: 'paragraph', html: 'Contoh Bob dengan pita merah muda langsung terlihat. Ubah resolusi dan skala untuk melihat kapan karakter tidak lagi muat atau piksel kehilangan keseragaman.' }, { type: 'title', level: 2, text: 'Apa yang diperiksa alat ini' }, { type: 'paragraph', html: 'Alat ini membandingkan dimensi dan footprint dalam tampilan terkontrol. Alat ini tidak membuka proyek engine, memeriksa atlas, mengukur perangkat, atau menjamin gerakan pixel perfect.' }, { type: 'title', level: 2, text: 'Alur singkat memilih skala' }, { type: 'paragraph', html: 'Muat sprite, pilih resolusi, coba 1x sampai 4x, dan pilih skala bilangan bulat terbesar yang masih menyisakan ruang. Ulangi pada resolusi game sebenarnya.' }, { type: 'tip', title: 'Pemeriksaan terakhir dilakukan di engine', html: 'Gunakan preview untuk mempersempit pilihan. Aktifkan filtering nearest, periksa padding atlas dan posisi kamera, lalu uji beberapa resolusi.' },
  ],
  faqTitle: 'Pertanyaan tentang skala sprite', faq, bibliographyTitle: 'Referensi pixel art', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
