import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Che cosa significa pixel per unità in un gioco?', answer: 'I pixel per unità, o PPU, indicano quanti pixel della texture rappresentano una unità del mondo. Una densità coerente mantiene sprite, tile e camera su una scala prevedibile.' },
  { question: 'Perché sono importanti le scale intere?', answer: 'Una scala intera assegna a ogni pixel sorgente lo stesso numero intero di pixel sullo schermo. Le frazioni possono creare bordi irregolari o sfocatura.' },
  { question: 'Che cos è il pixel bleeding?', answer: 'È un colore indesiderato preso da un texel vicino o da un altra zona dell atlas. Filtro, bordi, movimento subpixel e margine insufficiente possono causarlo.' },
  { question: 'Come uso la scala consigliata?', answer: 'Usala come candidata che entra nella risoluzione ed è vicina al tuo obiettivo. Poi verifica nel motore filtro nearest, allineamento della camera e margine dell atlas.' },
  { question: 'Il planner sceglie il PPU corretto per ogni motore?', answer: 'No. È un aiuto matematico trasparente. Camera, importazione, mipmap, arrotondamento e pixel snapping cambiano da motore a motore e richiedono un test reale.' },
];
const howTo = [
  { name: 'Scegliere lo schermo di destinazione', text: 'Inserisci larghezza e altezza della vista di gioco o della risoluzione di riferimento in pixel.' },
  { name: 'Caricare lo sprite', text: 'Scegli un immagine per rilevare le dimensioni native. Puoi anche usare lo sprite Bob incluso.' },
  { name: 'Scegliere una scala', text: 'Sposta il cursore o scegli un preset. I moltiplicatori interi sono i candidati più nitidi.' },
  { name: 'Leggere la preview', text: 'Controlla footprint, PPU orizzontale e verticale, mondo visibile e avviso di bleeding.' },
  { name: 'Provare nel motore', text: 'Verifica la scelta con filtro nearest, camera allineata, margine dell atlas e risoluzioni reali.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planner dei pixel per unità per giochi', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Provare la scala di uno sprite pixel art', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'planner-pixel-per-unita-sprite-giochi', title: 'Planner dei pixel per unità per sprite di giochi', description: 'Carica uno sprite o usa l esempio di Bob per vedere il footprint a diverse scale intere, confrontare il PPU e trovare il rischio di pixel bleeding.',
  ui: {
    inputsTitle: 'Carica e prova il tuo sprite', uploadTitle: 'La tua immagine sorgente', uploadHint: 'Scegli PNG, GIF, WebP o JPEG. Le dimensioni native alimentano ogni preview.', chooseSpriteLabel: 'Scegli sprite', noSpriteLabel: 'Nessuno sprite caricato', defaultSpriteLabel: 'Sprite Bob di esempio', loadedSpriteLabel: 'Caricato', clearSpriteLabel: 'Rimuovi sprite', displayWidthLabel: 'Larghezza schermo px', displayHeightLabel: 'Altezza schermo px', spriteWidthLabel: 'Larghezza sprite px', spriteHeightLabel: 'Altezza sprite px', worldWidthLabel: 'Larghezza sprite in unità', worldHeightLabel: 'Altezza sprite in unità', targetScaleLabel: 'Scala obiettivo sullo schermo', targetScaleHint: 'Pixel sullo schermo per ogni pixel della texture.', resolutionPresetsLabel: 'Risoluzioni di riferimento', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Scale rapide', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Ripristina valori', fieldTitle: 'Guardalo a più dimensioni', fieldCaption: 'L immagine caricata usa lo scaling nearest per valutare il footprint reale a ogni moltiplicatore intero.', previewPlaceholder: 'Carica uno sprite per iniziare il test visivo', previewScaleLabel: 'Scala preview', sourceImageAlt: 'Preview dello sprite caricato', viewportLabel: 'Schermo', spriteLabel: 'Sprite renderizzato', crispTitle: 'Scale nitide', crispCaption: 'I moltiplicatori interi mantengono uniformi i pixel. I passaggi grigi superano lo schermo dichiarato.', fitLabel: 'Entra nello schermo:', yesLabel: 'sì', noLabel: 'no', recommendedLabel: 'adattamento vicino', summaryTitle: 'Riepilogo del piano', ppuXLabel: 'PPU orizzontale', ppuYLabel: 'PPU verticale', viewportWorldLabel: 'Mondo visibile', fitScaleLabel: 'Scala massima adatta', bleedingRiskLabel: 'Rischio bleeding', lowRisk: 'Basso', mediumRisk: 'Medio', highRisk: 'Alto', riskLowMessage: 'Gli assi sono allineati e la scala obiettivo è intera e adatta. Controlla comunque filtro e margine dell atlas.', riskMediumMessage: 'L obiettivo si adatta in modo imperfetto. Esamina la differenza tra gli assi e le scale evidenziate.', riskHighMessage: 'La scala può creare campionamento irregolare. Preferisci un moltiplicatore intero e controlla le dimensioni.', alignmentLabel: 'Nota sul campionamento', tableTitle: 'Registro accessibile delle scale', tableScale: 'Scala', tableWidth: 'Larghezza renderizzata', tableHeight: 'Altezza renderizzata', tableFits: 'Entra nello schermo', modelNote: 'Il PPU è calcolato come pixel renderizzati dello sprite divisi per la sua dimensione in unità su ogni asse. Il rischio di bleeding è un euristico, non una verifica della texture o una garanzia del motore.', privacyDisclosure: 'Il file viene elaborato in questo browser. Sprite, file di progetto e telemetria non vengono inviati.', statusReady: 'Preview aggiornata', unitPixels: 'px', unitUnits: 'unità',
  },
  seo: [
    { type: 'title', level: 2, text: 'Trasforma la dimensione dello sprite in una scelta di scala' }, { type: 'paragraph', html: 'Uno sprite ha la dimensione del bitmap e quella che occupa nel mondo di gioco. Il PPU collega queste misure. La preview mostra la conseguenza visiva invece di lasciare decidere a un numero astratto.' }, { type: 'paragraph', html: 'Carica un immagine reale per usare le sue dimensioni native. Lo strumento moltiplica ogni asse per la scala scelta e calcola la parte di mondo visibile nella risoluzione dichiarata.' }, { type: 'title', level: 2, text: 'Cosa osservare nella preview' }, { type: 'list', items: ['Confronta il footprint con lo schermo di riferimento.', 'Prova prima le scale intere per pixel uniformi.', 'Usa entrambi i PPU per trovare stiramenti involontari.', 'Considera il bleeding un segnale per provare il motore.'] }, { type: 'title', level: 2, text: 'Perché le scale intere sono spesso più pulite' }, { type: 'paragraph', html: 'A 3x ogni pixel sorgente occupa tre pixel sullo schermo. A 2,5x il renderer deve distribuire larghezze diverse. Nearest evita di mescolare i colori, ma non corregge una camera tra posizioni di pixel.' }, { type: 'table', headers: ['Segnale', 'Lettura', 'Decisione successiva'], rows: [['PPU uguale', 'I due assi hanno la stessa densità.', 'Confronta tile e griglia del progetto.'], ['Scala frazionaria', 'Il footprint non usa un intero.', 'Prova l intero più vicino.'], ['Non entra', 'Lo sprite supera lo schermo.', 'Riduci la scala o aumenta la risoluzione.']] }, { type: 'title', level: 2, text: 'Distinguere il bleeding dalla semplice dimensione' }, { type: 'paragraph', html: 'Il pixel bleeding nasce spesso da texel vicini nell atlas, filtro sui bordi o coordinate della camera non allineate. Per la sfocatura controlla il filtro; per le cuciture controlla anche margine e limiti dell atlas.' }, { type: 'title', level: 2, text: 'Imparare con lo sprite Bob' }, { type: 'paragraph', html: 'L esempio Bob con il fiocco rosa è visibile subito. Cambia risoluzione e scala per vedere quando il personaggio non entra più o i pixel perdono uniformità.' }, { type: 'title', level: 2, text: 'Cosa verifica e cosa non verifica lo strumento' }, { type: 'paragraph', html: 'Lo strumento confronta dimensioni e footprint in una vista controllata. Non apre un progetto, non ispeziona un atlas, non misura un dispositivo e non garantisce movimento pixel perfect.' }, { type: 'title', level: 2, text: 'Un percorso breve per scegliere la scala' }, { type: 'paragraph', html: 'Carica lo sprite, scegli la risoluzione, prova da 1x a 4x e usa la scala intera più grande che lasci spazio. Ripeti poi con le risoluzioni realmente supportate.' }, { type: 'tip', title: 'L ultima verifica avviene nel motore', html: 'Usa la preview per restringere la scelta. Attiva poi il filtro nearest, controlla margine dell atlas e allineamento della camera, quindi prova più risoluzioni.' },
  ],
  faqTitle: 'Domande sullo scaling degli sprite', faq, bibliographyTitle: 'Riferimenti sul pixel art', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
