import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Wat betekent pixels per eenheid in een game?', answer: 'Pixels per eenheid, of PPU, geeft aan hoeveel textuurpixels één wereldeenheid voorstellen. Een vaste dichtheid houdt sprites, tegels en camera op een voorspelbare schaal.' },
  { question: 'Waarom zijn gehele schalen belangrijk?', answer: 'Een gehele schaal geeft elke bronpixel hetzelfde gehele aantal schermpixels. Breukschalen kunnen ongelijke randen of onscherpte veroorzaken.' },
  { question: 'Wat is pixel bleeding?', answer: 'Dat is ongewenste kleur van een naburige texel of een ander atlasgebied. Filtering, randen, subpixelbeweging en te weinig marge kunnen dit veroorzaken.' },
  { question: 'Hoe gebruik ik de aanbevolen schaal?', answer: 'Gebruik haar als kandidaat die binnen de resolutie past en dicht bij je doel ligt. Controleer daarna nearest-filtering, camera-uitlijning en atlasmarge in de engine.' },
  { question: 'Kiest de planner de juiste PPU voor elke engine?', answer: 'Nee. Dit is een transparante rekentool. Camera, import, mipmaps, afronding en pixel snapping verschillen per engine en moeten echt worden getest.' },
];
const howTo = [
  { name: 'Kies het doelbeeld', text: 'Voer de breedte en hoogte van de gameweergave of referentieresolutie in pixels in.' },
  { name: 'Laad de sprite', text: 'Kies een afbeelding zodat de oorspronkelijke afmetingen worden gevonden. Je kunt ook de Bob-sprite gebruiken.' },
  { name: 'Kies een schaal', text: 'Gebruik de schuifregelaar of een preset. Gehele vermenigvuldigers zijn de scherpste kandidaten.' },
  { name: 'Lees de preview', text: 'Controleer de sprite-footprint, horizontale en verticale PPU, zichtbare wereld en bleeding-waarschuwing.' },
  { name: 'Test in de engine', text: 'Controleer de keuze met nearest-filtering, een uitgelijnde camera, atlasmarge en echte spelresoluties.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planner voor pixels per eenheid in games', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Pixel-art-spriteschaling testen', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'pixels-per-eenheid-sprite-planner-games', title: 'Planner voor pixels per eenheid voor gamesprites', description: 'Upload een sprite of gebruik het Bob-voorbeeld om footprints op gehele schalen te bekijken, PPU te vergelijken en pixel bleeding te vinden.',
  ui: {
    inputsTitle: 'Laad en test je sprite', uploadTitle: 'Je bronafbeelding', uploadHint: 'Kies PNG, GIF, WebP of JPEG. De oorspronkelijke afmetingen sturen elke preview.', chooseSpriteLabel: 'Sprite kiezen', noSpriteLabel: 'Nog geen sprite geladen', defaultSpriteLabel: 'Bob-voorbeeldsprite', loadedSpriteLabel: 'Geladen', clearSpriteLabel: 'Sprite verwijderen', displayWidthLabel: 'Schermbreedte px', displayHeightLabel: 'Schermhoogte px', spriteWidthLabel: 'Spritebreedte px', spriteHeightLabel: 'Spritehoogte px', worldWidthLabel: 'Spritebreedte in eenheden', worldHeightLabel: 'Spritehoogte in eenheden', targetScaleLabel: 'Doelschaal op scherm', targetScaleHint: 'Schermpixels voor elke pixel van de textuur.', resolutionPresetsLabel: 'Referentieresoluties', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Snelle schalen', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Waarden herstellen', fieldTitle: 'Bekijk in verschillende groottes', fieldCaption: 'De geladen afbeelding wordt met nearest-schaling weergegeven zodat je de echte footprint per gehele vermenigvuldiger kunt beoordelen.', previewPlaceholder: 'Laad een sprite om de visuele test te starten', previewScaleLabel: 'Preview-schaal', sourceImageAlt: 'Preview van geladen sprite', viewportLabel: 'Scherm', spriteLabel: 'Gerenderde sprite', crispTitle: 'Scherpe schalen', crispCaption: 'Gehele vermenigvuldigers houden pixels gelijk. Grijze stappen overschrijden het opgegeven scherm.', fitLabel: 'Past op scherm:', yesLabel: 'ja', noLabel: 'nee', recommendedLabel: 'dichtste passende', summaryTitle: 'Plansamenvatting', ppuXLabel: 'Horizontale PPU', ppuYLabel: 'Verticale PPU', viewportWorldLabel: 'Zichtbare wereld', fitScaleLabel: 'Grootste passende schaal', bleedingRiskLabel: 'Bleeding-risico', lowRisk: 'Laag', mediumRisk: 'Middel', highRisk: 'Hoog', riskLowMessage: 'De assen zijn uitgelijnd en de gehele doelschaal past op het scherm. Controleer toch filtering en atlasmarge.', riskMediumMessage: 'Het doel past niet perfect. Bekijk het verschil tussen de assen en de gemarkeerde schalen.', riskHighMessage: 'Deze schaal kan ongelijke sampling geven. Kies een gehele vermenigvuldiger en controleer de afmetingen.', alignmentLabel: 'Opmerking over sampling', tableTitle: 'Toegankelijk schaaloverzicht', tableScale: 'Schaal', tableWidth: 'Gerenderde breedte', tableHeight: 'Gerenderde hoogte', tableFits: 'Past op scherm', modelNote: 'PPU wordt berekend als gerenderde spritepixels gedeeld door de spritegrootte in eenheden per as. Bleeding-risico is een heuristiek, geen textuurcontrole of enginegarantie.', privacyDisclosure: 'Het bestand wordt in deze browser verwerkt. Sprites, projectbestanden en telemetrie worden niet verzonden.', statusReady: 'Preview bijgewerkt', unitPixels: 'px', unitUnits: 'eenheden',
  },
  seo: [
    { type: 'title', level: 2, text: 'Maak van spritegrootte een schaalbeslissing' }, { type: 'paragraph', html: 'Een sprite heeft de bitmapgrootte en de grootte die hij in de spelwereld inneemt. PPU verbindt die maten. De preview toont het visuele gevolg in plaats van alleen een abstract getal.' }, { type: 'paragraph', html: 'Laad een echte afbeelding zodat de oorspronkelijke maten worden gebruikt. De tool vermenigvuldigt beide assen met de gekozen schaal en berekent de zichtbare wereld.' }, { type: 'title', level: 2, text: 'Wat je in de preview bekijkt' }, { type: 'list', items: ['Vergelijk de footprint met het referentiescherm.', 'Test gehele schalen eerst voor gelijkmatige pixels.', 'Gebruik beide PPU-waarden om onbedoeld uitrekken te vinden.', 'Zie de bleeding-waarschuwing als signaal voor een enginetest.'] }, { type: 'title', level: 2, text: 'Waarom gehele schalen vaak schoner zijn' }, { type: 'paragraph', html: 'Bij 3x neemt elke bronpixel drie schermpixels in. Bij 2,5x moet de renderer verschillende breedtes verdelen. Nearest voorkomt kleurmenging, maar corrigeert geen camera tussen pixelposities.' }, { type: 'table', headers: ['Signaal', 'Betekenis', 'Volgende keuze'], rows: [['Gelijke PPU', 'Beide assen hebben dezelfde dichtheid.', 'Vergelijk met tegels en projectraster.'], ['Breukschaal', 'De footprint gebruikt geen geheel getal.', 'Test de dichtstbijzijnde gehele schaal.'], ['Past niet', 'De sprite overschrijdt het scherm.', 'Verlaag de schaal of verhoog de resolutie.']] }, { type: 'title', level: 2, text: 'Bleeding onderscheiden van grootte' }, { type: 'paragraph', html: 'Pixel bleeding komt vaak door naburige texels in een atlas, filtering aan randen of niet-uitgelijnde cameracoördinaten. Controleer bij onscherpte de filter en bij naden ook marge en grenzen.' }, { type: 'title', level: 2, text: 'Leer de werkwijze met de Bob-sprite' }, { type: 'paragraph', html: 'Het voorbeeld van Bob met de roze strik staat meteen klaar. Verander resolutie en schaal om te zien wanneer het personage niet meer past of pixels ongelijk worden.' }, { type: 'title', level: 2, text: 'Wat deze tool wel en niet controleert' }, { type: 'paragraph', html: 'De tool vergelijkt maten en footprints in een gecontroleerde weergave. Hij opent geen engineproject, inspecteert geen atlas, meet geen apparaat en garandeert geen pixel-perfecte beweging.' }, { type: 'title', level: 2, text: 'Een korte route naar een schaal' }, { type: 'paragraph', html: 'Laad de sprite, kies de resolutie, test 1x tot 4x en kies de grootste gehele schaal met ruimte over. Herhaal dit voor de echte spelresoluties.' }, { type: 'tip', title: 'De laatste controle gebeurt in de engine', html: 'Gebruik de preview om de keuze te beperken. Activeer daarna nearest-filtering, controleer atlasmarge en camera-uitlijning en test meerdere resoluties.' },
  ],
  faqTitle: 'Vragen over spriteschaling', faq, bibliographyTitle: 'Bronnen over pixel art', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
