import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Co oznacza liczba pikseli na jednostkę w grze?', answer: 'Piksele na jednostkę, czyli PPU, mówią, ile pikseli tekstury reprezentuje jedną jednostkę świata. Spójna gęstość pomaga utrzymać przewidywalną skalę spriteów, kafelków i kamery.' },
  { question: 'Dlaczego skale całkowite są ważne?', answer: 'Skala całkowita daje każdemu pikselowi źródłowemu tę samą całkowitą liczbę pikseli ekranu. Ułamki mogą tworzyć nierówne krawędzie lub rozmycie.' },
  { question: 'Czym jest pixel bleeding?', answer: 'To niepożądany kolor pobrany z sąsiedniego teksela albo innego obszaru atlasu. Filtrowanie, krawędzie, ruch subpikselowy i brak marginesu mogą go powodować.' },
  { question: 'Jak używać zalecanej skali?', answer: 'Potraktuj ją jako kandydata, który mieści się w rozdzielczości i jest blisko celu. Potem sprawdź w silniku filtr nearest, ustawienie kamery i margines atlasu.' },
  { question: 'Czy planista wybiera właściwe PPU dla każdego silnika?', answer: 'Nie. To przejrzysta pomoc arytmetyczna. Kamera, import, mipmapy, zaokrąglenia i pixel snapping różnią się między silnikami i wymagają testu.' },
];
const howTo = [
  { name: 'Wybierz ekran docelowy', text: 'Podaj szerokość i wysokość widoku gry lub rozdzielczości referencyjnej w pikselach.' },
  { name: 'Wczytaj sprite', text: 'Wybierz obraz, aby wykryć jego natywne wymiary. Możesz też użyć dołączonego spritea Boba.' },
  { name: 'Wybierz skalę', text: 'Przesuń suwak albo wybierz preset. Całkowite mnożniki są najostrzejszymi kandydatami.' },
  { name: 'Odczytaj podgląd', text: 'Sprawdź footprint spritea, poziome i pionowe PPU, widoczny świat oraz ostrzeżenie o bleeding.' },
  { name: 'Przetestuj w silniku', text: 'Zweryfikuj wybór z filtrem nearest, wyrównaną kamerą, marginesem atlasu i prawdziwymi rozdzielczościami.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planista pikseli na jednostkę dla gier', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Sprawdzanie skali spritea pixel art', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'planista-pikseli-na-jednostke-sprite-gra', title: 'Planista pikseli na jednostkę dla spriteów gier', description: 'Wczytaj sprite albo użyj przykładu Boba, aby zobaczyć footprint przy skalach całkowitych, porównać PPU i znaleźć ryzyko pixel bleeding.',
  ui: {
    inputsTitle: 'Wczytaj i sprawdź sprite', uploadTitle: 'Twój obraz źródłowy', uploadHint: 'Wybierz PNG, GIF, WebP lub JPEG. Natywne wymiary sterują każdym podglądem.', chooseSpriteLabel: 'Wybierz sprite', noSpriteLabel: 'Nie wczytano spritea', defaultSpriteLabel: 'Przykładowy sprite Boba', loadedSpriteLabel: 'Wczytano', clearSpriteLabel: 'Usuń sprite', displayWidthLabel: 'Szerokość ekranu px', displayHeightLabel: 'Wysokość ekranu px', spriteWidthLabel: 'Szerokość spritea px', spriteHeightLabel: 'Wysokość spritea px', worldWidthLabel: 'Szerokość spritea w jednostkach', worldHeightLabel: 'Wysokość spritea w jednostkach', targetScaleLabel: 'Docelowa skala ekranu', targetScaleHint: 'Piksele ekranu na każdy piksel tekstury.', resolutionPresetsLabel: 'Rozdzielczości referencyjne', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Szybkie skale', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Przywróć wartości', fieldTitle: 'Zobacz różne rozmiary', fieldCaption: 'Wczytany obraz jest renderowany ze skalowaniem nearest, aby ocenić rzeczywisty footprint przy każdym całkowitym mnożniku.', previewPlaceholder: 'Wczytaj sprite, aby rozpocząć test wizualny', previewScaleLabel: 'Skala podglądu', sourceImageAlt: 'Podgląd wczytanego spritea', viewportLabel: 'Ekran', spriteLabel: 'Wyrenderowany sprite', crispTitle: 'Ostre skale', crispCaption: 'Całkowite mnożniki zachowują równy rozmiar pikseli. Szare kroki przekraczają podany ekran.', fitLabel: 'Mieści się na ekranie:', yesLabel: 'tak', noLabel: 'nie', recommendedLabel: 'najbliższe dopasowanie', summaryTitle: 'Podsumowanie planu', ppuXLabel: 'PPU poziome', ppuYLabel: 'PPU pionowe', viewportWorldLabel: 'Widoczny świat', fitScaleLabel: 'Największa pasująca skala', bleedingRiskLabel: 'Ryzyko bleeding', lowRisk: 'Niskie', mediumRisk: 'Średnie', highRisk: 'Wysokie', riskLowMessage: 'Osie są wyrównane, a całkowita skala mieści się na ekranie. Nadal sprawdź filtrowanie i margines atlasu.', riskMediumMessage: 'Cel pasuje niedokładnie. Sprawdź różnicę osi i wyróżnione skale.', riskHighMessage: 'Skala może tworzyć nierówne próbkowanie. Wybierz całkowity mnożnik i sprawdź wymiary spritea.', alignmentLabel: 'Uwaga o próbkowaniu', tableTitle: 'Dostępny rejestr skal', tableScale: 'Skala', tableWidth: 'Wyrenderowana szerokość', tableHeight: 'Wyrenderowana wysokość', tableFits: 'Mieści się na ekranie', modelNote: 'PPU to wyrenderowane piksele spritea podzielone przez jego rozmiar w jednostkach na każdej osi. Ryzyko bleeding jest heurystyką, a nie inspekcją tekstury ani gwarancją silnika.', privacyDisclosure: 'Plik jest przetwarzany w tej przeglądarce. Spritey, pliki projektu i telemetria nie są wysyłane.', statusReady: 'Podgląd zaktualizowany', unitPixels: 'px', unitUnits: 'jednostki',
  },
  seo: [
    { type: 'title', level: 2, text: 'Zamień rozmiar spritea w decyzję o skali' }, { type: 'paragraph', html: 'Sprite ma rozmiar bitmapy oraz rozmiar zajmowany w świecie gry. PPU łączy te miary. Podgląd pokazuje skutek wizualny zamiast pozostawiać decyzję abstrakcyjnej liczbie.' }, { type: 'paragraph', html: 'Wczytaj prawdziwy obraz, aby użyć jego natywnych wymiarów. Narzędzie mnoży obie osie przez wybraną skalę i oblicza widoczny fragment świata.' }, { type: 'title', level: 2, text: 'Co obserwować w podglądzie' }, { type: 'list', items: ['Porównaj footprint z ekranem referencyjnym.', 'Najpierw sprawdź skale całkowite.', 'Użyj obu wartości PPU, aby znaleźć niezamierzone rozciągnięcie.', 'Potraktuj ostrzeżenie bleeding jako sygnał do testu w silniku.'] }, { type: 'title', level: 2, text: 'Dlaczego skale całkowite są czystsze' }, { type: 'paragraph', html: 'Przy 3x każdy piksel źródłowy zajmuje trzy piksele ekranu. Przy 2,5x renderer musi rozdzielać różne szerokości. Nearest nie miesza kolorów, ale nie naprawia kamery ustawionej między pikselami.' }, { type: 'table', headers: ['Sygnał', 'Odczyt', 'Następna decyzja'], rows: [['Równe PPU', 'Obie osie mają tę samą gęstość.', 'Porównaj z kafelkami i siatką projektu.'], ['Skala ułamkowa', 'Footprint nie używa liczby całkowitej.', 'Sprawdź najbliższą skalę całkowitą.'], ['Nie mieści się', 'Sprite przekracza ekran.', 'Zmniejsz skalę albo zwiększ rozdzielczość.']] }, { type: 'title', level: 2, text: 'Odróżnij bleeding od rozmiaru' }, { type: 'paragraph', html: 'Pixel bleeding często pochodzi z sąsiednich tekseli atlasu, filtrowania przy krawędziach lub niewyrównanych współrzędnych kamery. Przy rozmyciu sprawdź filtr, a przy szwach także margines i granice.' }, { type: 'title', level: 2, text: 'Naucz się na spricie Boba' }, { type: 'paragraph', html: 'Przykład Boba z różową kokardą widać od razu. Zmieniaj rozdzielczość i skalę, aby zobaczyć, kiedy postać przestaje się mieścić albo piksele tracą równość.' }, { type: 'title', level: 2, text: 'Co narzędzie sprawdza, a czego nie' }, { type: 'paragraph', html: 'Narzędzie porównuje wymiary i footprinty w kontrolowanym widoku. Nie otwiera projektu silnika, nie bada atlasu, nie mierzy urządzenia i nie gwarantuje ruchu pixel perfect.' }, { type: 'title', level: 2, text: 'Krótki sposób wyboru skali' }, { type: 'paragraph', html: 'Wczytaj sprite, wybierz rozdzielczość, sprawdź 1x do 4x i wybierz największą skalę całkowitą z wolnym miejscem. Powtórz dla rozdzielczości obsługiwanych przez grę.' }, { type: 'tip', title: 'Ostatni test wykonaj w silniku', html: 'Użyj podglądu, aby zawęzić wybór. Potem włącz filtr nearest, sprawdź margines atlasu i ustawienie kamery oraz przetestuj kilka rozdzielczości.' },
  ],
  faqTitle: 'Pytania o skalowanie spriteów', faq, bibliographyTitle: 'Źródła o pixel arcie', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
