import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'O que significa pixels por unidade em um jogo?', answer: 'Pixels por unidade, ou PPU, indica quantos pixels da textura representam uma unidade do mundo. Uma densidade coerente mantém sprites, tiles e câmera numa escala previsível.' },
  { question: 'Por que escalas inteiras são importantes?', answer: 'Uma escala inteira dá a cada pixel de origem o mesmo número inteiro de pixels na tela. Frações podem criar bordas irregulares ou suavização.' },
  { question: 'O que é pixel bleeding?', answer: 'É uma cor indesejada de um texel vizinho ou de outra área do atlas. Filtro, bordas, movimento subpixel e pouca margem podem causar esse problema.' },
  { question: 'Como uso a escala recomendada?', answer: 'Use-a como candidata que cabe na resolução e fica próxima do alvo. Depois confira no motor o filtro nearest, o alinhamento da câmera e a margem do atlas.' },
  { question: 'O planejador escolhe o PPU correto para todo motor?', answer: 'Não. É uma ajuda matemática transparente. Câmera, importação, mipmaps, arredondamento e pixel snapping variam e exigem um teste real.' },
];
const howTo = [
  { name: 'Escolher a tela de destino', text: 'Informe a largura e a altura da tela do jogo ou da resolução de referência em pixels.' },
  { name: 'Carregar o sprite', text: 'Escolha uma imagem para detectar suas dimensões nativas. Você também pode usar o sprite Bob incluído.' },
  { name: 'Escolher uma escala', text: 'Mova o controle ou escolha um preset. Multiplicadores inteiros são os candidatos mais nítidos.' },
  { name: 'Ler a preview', text: 'Confira o footprint do sprite, o PPU horizontal e vertical, o mundo visível e o aviso de bleeding.' },
  { name: 'Testar no motor', text: 'Valide a escolha com filtro nearest, câmera alinhada, margem de atlas e resoluções reais.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planejador de pixels por unidade para jogos', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Testar a escala de um sprite pixel art', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'planejador-pixels-por-unidade-sprite-jogos', title: 'Planejador de pixels por unidade para sprites de jogos', description: 'Envie um sprite ou use o exemplo do Bob para ver o footprint em várias escalas inteiras, comparar o PPU e encontrar risco de pixel bleeding.',
  ui: {
    inputsTitle: 'Carregue e teste seu sprite', uploadTitle: 'Sua imagem de origem', uploadHint: 'Escolha PNG, GIF, WebP ou JPEG. As dimensões nativas alimentam cada preview.', chooseSpriteLabel: 'Escolher sprite', noSpriteLabel: 'Nenhum sprite carregado', defaultSpriteLabel: 'Sprite Bob de exemplo', loadedSpriteLabel: 'Carregado', clearSpriteLabel: 'Remover sprite', displayWidthLabel: 'Largura da tela px', displayHeightLabel: 'Altura da tela px', spriteWidthLabel: 'Largura do sprite px', spriteHeightLabel: 'Altura do sprite px', worldWidthLabel: 'Largura do sprite em unidades', worldHeightLabel: 'Altura do sprite em unidades', targetScaleLabel: 'Escala alvo na tela', targetScaleHint: 'Pixels na tela para cada pixel da textura.', resolutionPresetsLabel: 'Resoluções de referência', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Escalas rápidas', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Redefinir valores', fieldTitle: 'Veja em vários tamanhos', fieldCaption: 'A imagem carregada usa escala nearest para avaliar seu footprint real em cada multiplicador inteiro.', previewPlaceholder: 'Carregue um sprite para começar o teste visual', previewScaleLabel: 'Escala da preview', sourceImageAlt: 'Preview do sprite carregado', viewportLabel: 'Tela', spriteLabel: 'Sprite renderizado', crispTitle: 'Escalas nítidas', crispCaption: 'Multiplicadores inteiros mantêm os pixels uniformes. Etapas cinzentas ultrapassam a tela declarada.', fitLabel: 'Cabe na tela:', yesLabel: 'sim', noLabel: 'não', recommendedLabel: 'ajuste mais próximo', summaryTitle: 'Resumo do plano', ppuXLabel: 'PPU horizontal', ppuYLabel: 'PPU vertical', viewportWorldLabel: 'Mundo visível', fitScaleLabel: 'Maior escala que cabe', bleedingRiskLabel: 'Risco de bleeding', lowRisk: 'Baixo', mediumRisk: 'Médio', highRisk: 'Alto', riskLowMessage: 'Os eixos estão alinhados e a escala alvo é inteira e cabe na tela. Confira ainda o filtro e a margem do atlas.', riskMediumMessage: 'O alvo se ajusta de forma imperfeita. Examine a diferença entre os eixos e as escalas destacadas.', riskHighMessage: 'A escala pode criar amostragem irregular. Prefira um multiplicador inteiro e confira as dimensões.', alignmentLabel: 'Nota de amostragem', tableTitle: 'Registro acessível de escalas', tableScale: 'Escala', tableWidth: 'Largura renderizada', tableHeight: 'Altura renderizada', tableFits: 'Cabe na tela', modelNote: 'O PPU é calculado como pixels renderizados do sprite divididos pelo seu tamanho em unidades em cada eixo. O risco de bleeding é uma heurística, não uma inspeção da textura nem uma garantia do motor.', privacyDisclosure: 'O arquivo é processado neste navegador. Sprites, arquivos do projeto e telemetria não são enviados.', statusReady: 'Preview atualizada', unitPixels: 'px', unitUnits: 'unidades',
  },
  seo: [
    { type: 'title', level: 2, text: 'Transforme o tamanho do sprite em uma decisão de escala' }, { type: 'paragraph', html: 'Um sprite tem o tamanho do bitmap e o tamanho que ocupa no mundo do jogo. O PPU conecta essas medidas. A preview mostra a consequência visual em vez de deixar uma cifra abstrata decidir.' }, { type: 'paragraph', html: 'Carregue uma imagem real para usar suas dimensões nativas. A ferramenta multiplica cada eixo pela escala escolhida e calcula a parte do mundo visível na resolução informada.' }, { type: 'title', level: 2, text: 'O que observar na preview' }, { type: 'list', items: ['Compare o footprint com a tela de referência.', 'Teste primeiro escalas inteiras para manter pixels uniformes.', 'Use os dois PPUs para encontrar deformações não intencionais.', 'Trate o aviso de bleeding como sinal para testar o motor.'] }, { type: 'title', level: 2, text: 'Por que escalas inteiras costumam ser mais limpas' }, { type: 'paragraph', html: 'Em 3x, cada pixel de origem ocupa três pixels da tela. Em 2,5x, o renderizador precisa distribuir larguras diferentes. Nearest evita misturar cores, mas não corrige uma câmera entre posições de pixel.' }, { type: 'table', headers: ['Sinal', 'Leitura', 'Próxima decisão'], rows: [['PPU igual', 'Os dois eixos têm a mesma densidade.', 'Compare com tiles e a grade do projeto.'], ['Escala fracionária', 'O footprint não usa um inteiro.', 'Teste o inteiro mais próximo.'], ['Não cabe', 'O sprite ultrapassa a tela.', 'Reduza a escala ou aumente a resolução.']] }, { type: 'title', level: 2, text: 'Separe bleeding de tamanho' }, { type: 'paragraph', html: 'Pixel bleeding costuma vir de texels vizinhos no atlas, filtro nas bordas ou coordenadas de câmera desalinhadas. Para desfoque, confira o filtro; para emendas, confira também margem e limites.' }, { type: 'title', level: 2, text: 'Aprenda com o sprite Bob' }, { type: 'paragraph', html: 'O exemplo do Bob com o laço rosa aparece logo ao abrir. Mude resolução e escala para ver quando o personagem deixa de caber ou os pixels perdem uniformidade.' }, { type: 'title', level: 2, text: 'O que a ferramenta valida e o que não valida' }, { type: 'paragraph', html: 'A ferramenta compara dimensões e footprints em uma vista controlada. Não abre um projeto, não inspeciona um atlas, não mede um dispositivo e não garante movimento pixel perfect.' }, { type: 'title', level: 2, text: 'Um fluxo curto para escolher a escala' }, { type: 'paragraph', html: 'Carregue o sprite, escolha a resolução, teste de 1x a 4x e use a maior escala inteira que deixe espaço. Repita com as resoluções suportadas pelo jogo.' }, { type: 'tip', title: 'A última verificação acontece no motor', html: 'Use a preview para restringir a escolha. Depois ative filtro nearest, confira a margem do atlas e o alinhamento da câmera e teste várias resoluções.' },
  ],
  faqTitle: 'Perguntas sobre escala de sprites', faq, bibliographyTitle: 'Referências de pixel art', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
