import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Vad betyder pixlar per enhet i ett spel?', answer: 'Pixlar per enhet, eller PPU, visar hur många texturpixlar som motsvarar en världsenhet. En jämn täthet håller sprites, tiles och kamera på en förutsägbar skala.' },
  { question: 'Varför är heltalskalor viktiga?', answer: 'En heltalsskala ger varje källpixel samma hela antal skärmpixlar. Bråkdelar kan skapa ojämna kanter eller oskärpa.' },
  { question: 'Vad är pixel bleeding?', answer: 'Det är oönskad färg från en närliggande texel eller atlasdel. Filtrering, kanter, subpixelrörelse och för liten marginal kan orsaka det.' },
  { question: 'Hur använder jag den rekommenderade skalan?', answer: 'Använd den som kandidat som ryms i upplösningen och ligger nära ditt mål. Kontrollera sedan nearest-filtrering, kamera och atlasmarginal i motorn.' },
  { question: 'Väljer planeraren rätt PPU för varje motor?', answer: 'Nej. Det är ett transparent räkneverktyg. Kamera, import, mipmaps, avrundning och pixel snapping varierar och kräver ett verkligt test.' },
];
const howTo = [
  { name: 'Välj målskärmen', text: 'Ange bredd och höjd för spelvyn eller referensupplösningen i pixlar.' },
  { name: 'Ladda en sprite', text: 'Välj en bild så att dess ursprungliga mått upptäcks. Du kan också använda Bobs exempel.' },
  { name: 'Välj skala', text: 'Flytta reglaget eller välj ett preset. Heltalsmultiplikatorer är de skarpaste kandidaterna.' },
  { name: 'Läs förhandsvisningen', text: 'Kontrollera sprite-footprint, horisontell och vertikal PPU, synlig värld och bleeding-varningen.' },
  { name: 'Testa i motorn', text: 'Bekräfta valet med nearest-filtrering, justerad kamera, atlasmarginal och verkliga upplösningar.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Planerare för pixlar per enhet i spel', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Testa skalning av en pixel art-sprite', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'planerare-pixlar-per-enhet-sprite-spel', title: 'Planerare för pixlar per enhet för spelsprites', description: 'Ladda upp en sprite eller använd Bobs exempel för att se footprint vid heltalsskalor, jämföra PPU och hitta risk för pixel bleeding.',
  ui: {
    inputsTitle: 'Ladda och testa din sprite', uploadTitle: 'Din källbild', uploadHint: 'Välj PNG, GIF, WebP eller JPEG. De ursprungliga måtten används i varje preview.', chooseSpriteLabel: 'Välj sprite', noSpriteLabel: 'Ingen sprite laddad', defaultSpriteLabel: 'Bobs exempelsprite', loadedSpriteLabel: 'Laddad', clearSpriteLabel: 'Ta bort sprite', displayWidthLabel: 'Skärmbredd px', displayHeightLabel: 'Skärmhöjd px', spriteWidthLabel: 'Spritebredd px', spriteHeightLabel: 'Spritehöjd px', worldWidthLabel: 'Spritebredd i enheter', worldHeightLabel: 'Spritehöjd i enheter', targetScaleLabel: 'Målskala på skärmen', targetScaleHint: 'Skärmpixlar för varje pixel i texturen.', resolutionPresetsLabel: 'Referensupplösningar', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Snabba skalor', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Återställ värden', fieldTitle: 'Se den i flera storlekar', fieldCaption: 'Den laddade bilden renderas med nearest-skalning så att du kan bedöma footprint vid varje heltalsmultiplikator.', previewPlaceholder: 'Ladda en sprite för att börja det visuella testet', previewScaleLabel: 'Preview-skala', sourceImageAlt: 'Förhandsvisning av laddad sprite', viewportLabel: 'Skärm', spriteLabel: 'Renderad sprite', crispTitle: 'Skarpa skalor', crispCaption: 'Heltalsmultiplikatorer håller pixlarna jämna. Grå steg överskrider den angivna skärmen.', fitLabel: 'Ryms på skärmen:', yesLabel: 'ja', noLabel: 'nej', recommendedLabel: 'närmast passande', summaryTitle: 'Plansammanfattning', ppuXLabel: 'Horisontell PPU', ppuYLabel: 'Vertikal PPU', viewportWorldLabel: 'Synlig värld', fitScaleLabel: 'Största passande skala', bleedingRiskLabel: 'Bleeding-risk', lowRisk: 'Låg', mediumRisk: 'Medel', highRisk: 'Hög', riskLowMessage: 'Axlarna är justerade och målskalan är ett heltal som ryms. Kontrollera ändå filtrering och atlasmarginal.', riskMediumMessage: 'Målet passar inte perfekt. Granska skillnaden mellan axlarna och de markerade skalorna.', riskHighMessage: 'Skalan kan ge ojämn sampling. Välj en heltalsmultiplikator och kontrollera sprite-måtten.', alignmentLabel: 'Samplingsnotis', tableTitle: 'Tillgängligt skalregister', tableScale: 'Skala', tableWidth: 'Renderad bredd', tableHeight: 'Renderad höjd', tableFits: 'Ryms på skärmen', modelNote: 'PPU beräknas som renderade spritepixlar delat med spritens storlek i enheter på varje axel. Bleeding-risk är en heuristik, inte en texturkontroll eller motorgaranti.', privacyDisclosure: 'Filen behandlas i denna webbläsare. Sprites, projektfiler och telemetri skickas inte.', statusReady: 'Preview uppdaterad', unitPixels: 'px', unitUnits: 'enheter',
  },
  seo: [
    { type: 'title', level: 2, text: 'Gör spritens storlek till ett skalbeslut' }, { type: 'paragraph', html: 'En sprite har bitmapens storlek och storleken den upptar i spelvärlden. PPU kopplar ihop måtten. Previewn visar det visuella resultatet i stället för att låta en abstrakt siffra avgöra.' }, { type: 'paragraph', html: 'Ladda en riktig bild för att använda dess ursprungliga mått. Verktyget multiplicerar sedan varje axel med vald skala och räknar ut den synliga världen.' }, { type: 'title', level: 2, text: 'Vad du ska se i previewn' }, { type: 'list', items: ['Jämför footprint med referensskärmen.', 'Testa heltalsskalor först för jämna pixlar.', 'Använd båda PPU-värdena för att hitta oavsiktlig uttänjning.', 'Se bleeding-varningen som en signal för ett motortest.'] }, { type: 'title', level: 2, text: 'Varför heltalsskalor ofta blir renare' }, { type: 'paragraph', html: 'Vid 3x upptar varje källpixel tre skärmpixlar. Vid 2,5x måste renderaren fördela olika bredder. Nearest blandar inte färger, men korrigerar inte en kamera mellan pixelpositioner.' }, { type: 'table', headers: ['Signal', 'Tolkning', 'Nästa beslut'], rows: [['Samma PPU', 'Båda axlarna har samma täthet.', 'Jämför med tiles och projektets rutnät.'], ['Bråkig skala', 'Footprint använder inte ett heltal.', 'Testa närmaste heltalsskala.'], ['Ryms inte', 'Spriten överskrider skärmen.', 'Minska skalan eller öka upplösningen.']] }, { type: 'title', level: 2, text: 'Skilj bleeding från storlek' }, { type: 'paragraph', html: 'Pixel bleeding kommer ofta från granntesel i ett atlas, filtrering vid kanter eller kamera som inte är justerad. Kontrollera filtret vid oskärpa och även marginaler och gränser vid sömmar.' }, { type: 'title', level: 2, text: 'Lär dig flödet med Bob-spriten' }, { type: 'paragraph', html: 'Bob-exemplet med den rosa rosetten syns direkt. Ändra upplösning och skala för att se när figuren inte längre ryms eller pixlarna blir ojämna.' }, { type: 'title', level: 2, text: 'Vad verktyget kontrollerar och inte kontrollerar' }, { type: 'paragraph', html: 'Verktyget jämför mått och footprints i en kontrollerad vy. Det öppnar inget motorprojekt, granskar inget atlas, mäter ingen enhet och garanterar inte pixel perfect-rörelse.' }, { type: 'title', level: 2, text: 'En kort väg till rätt skala' }, { type: 'paragraph', html: 'Ladda spriten, välj upplösning, prova 1x till 4x och välj största heltalsskala med luft kvar. Upprepa sedan för spelets verkliga upplösningar.' }, { type: 'tip', title: 'Det sista testet görs i motorn', html: 'Använd previewn för att begränsa valet. Aktivera sedan nearest, kontrollera atlasmarginal och kamera och testa flera upplösningar.' },
  ],
  faqTitle: 'Frågor om spriteskalning', faq, bibliographyTitle: 'Referenser om pixel art', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
