import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { GamePixelPerUnitPlannerUI } from '../ui';
import { bibliographyEntries } from '../bibliography';

const faq = [
  { question: 'Bir oyunda birim başına piksel ne demektir?', answer: 'Birim başına piksel veya PPU, bir dünya birimini kaç doku pikselinin temsil ettiğini gösterir. Tutarlı yoğunluk sprite, tile ve kameranın öngörülebilir ölçekte kalmasını sağlar.' },
  { question: 'Tam sayı ölçekleri neden önemlidir?', answer: 'Tam sayı ölçeği her kaynak pikseline ekranda aynı sayıda tam piksel verir. Kesirli ölçekler düzensiz kenarlara veya bulanıklığa yol açabilir.' },
  { question: 'Pixel bleeding nedir?', answer: 'Komşu bir texel veya atlas bölgesinden gelen istenmeyen renktir. Filtreleme, kenarlar, alt piksel hareketi ve yetersiz boşluk buna neden olabilir.' },
  { question: 'Önerilen ölçeği nasıl kullanırım?', answer: 'Çözünürlüğe sığan ve hedefe yakın olan aday olarak kullanın. Ardından motorda nearest filtresini, kamera hizasını ve atlas boşluğunu kontrol edin.' },
  { question: 'Planlayıcı her motor için doğru PPUyu seçer mi?', answer: 'Hayır. Bu şeffaf bir hesaplama yardımcısıdır. Kamera, içe aktarma, mipmap, yuvarlama ve pixel snapping motora göre değişir ve gerçek test ister.' },
];
const howTo = [
  { name: 'Hedef ekranı seçin', text: 'Oyun görünümünün veya referans çözünürlüğünün genişlik ve yüksekliğini piksel olarak girin.' },
  { name: 'Sprite yükleyin', text: 'Yerel boyutları algılamak için bir görsel seçin. Dahili Bob spriteını da kullanabilirsiniz.' },
  { name: 'Ölçek seçin', text: 'Kaydırıcıyı hareket ettirin veya hazır ayar seçin. Tam sayı çarpanları en net adaylardır.' },
  { name: 'Önizlemeyi okuyun', text: 'Sprite footprintini, yatay ve dikey PPUyu, görünür dünyayı ve bleeding uyarısını kontrol edin.' },
  { name: 'Motorda test edin', text: 'Seçimi nearest filtre, hizalı kamera, atlas boşluğu ve gerçek oyun çözünürlükleriyle doğrulayın.' },
];
const softwareApplication: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Oyunlar için birim başına piksel planlayıcı', applicationCategory: 'DeveloperApplication', operatingSystem: 'Any' };
const faqPage: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: 'Bir pixel art spriteının ölçeğini test etme', step: howTo.map((step) => ({ '@type': 'HowToStep', name: step.name, text: step.text })) };

export const content: ToolLocaleContent<GamePixelPerUnitPlannerUI> = {
  slug: 'oyun-sprite-birim-basina-piksel-planlayici', title: 'Oyun spriteı için birim başına piksel planlayıcı', description: 'Bir sprite yükleyin veya Bob örneğini kullanın; tam sayı ölçeklerinde footprinti görün, PPUyu karşılaştırın ve pixel bleeding riskini bulun.',
  ui: {
    inputsTitle: 'Sprite yükleyin ve test edin', uploadTitle: 'Kaynak görseliniz', uploadHint: 'PNG, GIF, WebP veya JPEG seçin. Yerel boyutlar tüm önizlemeleri besler.', chooseSpriteLabel: 'Sprite seç', noSpriteLabel: 'Henüz sprite yüklenmedi', defaultSpriteLabel: 'Bob örnek spriteı', loadedSpriteLabel: 'Yüklendi', clearSpriteLabel: 'Spriteı kaldır', displayWidthLabel: 'Ekran genişliği px', displayHeightLabel: 'Ekran yüksekliği px', spriteWidthLabel: 'Sprite genişliği px', spriteHeightLabel: 'Sprite yüksekliği px', worldWidthLabel: 'Sprite genişliği birim', worldHeightLabel: 'Sprite yüksekliği birim', targetScaleLabel: 'Hedef ekran ölçeği', targetScaleHint: 'Doku pikseli başına ekran pikseli.', resolutionPresetsLabel: 'Referans çözünürlükleri', preset320: '320 x 180', preset384: '384 x 216', preset640: '640 x 360', scalePresetsLabel: 'Hızlı ölçekler', scale1: '1x', scale2: '2x', scale3: '3x', scale4: '4x', scale6: '6x', resetLabel: 'Değerleri sıfırla', fieldTitle: 'Farklı boyutlarda görün', fieldCaption: 'Yüklenen görsel, her tam sayı çarpanındaki gerçek footprinti değerlendirmek için nearest ölçeklemeyle çizilir.', previewPlaceholder: 'Görsel teste başlamak için sprite yükleyin', previewScaleLabel: 'Önizleme ölçeği', sourceImageAlt: 'Yüklenen sprite önizlemesi', viewportLabel: 'Ekran', spriteLabel: 'Çizilen sprite', crispTitle: 'Keskin ölçekler', crispCaption: 'Tam sayı çarpanları pikselleri eşit tutar. Gri adımlar belirtilen ekranı aşar.', fitLabel: 'Ekrana sığar:', yesLabel: 'evet', noLabel: 'hayır', recommendedLabel: 'en yakın uyum', summaryTitle: 'Plan özeti', ppuXLabel: 'Yatay PPU', ppuYLabel: 'Dikey PPU', viewportWorldLabel: 'Görünen dünya', fitScaleLabel: 'Sığan en büyük ölçek', bleedingRiskLabel: 'Bleeding riski', lowRisk: 'Düşük', mediumRisk: 'Orta', highRisk: 'Yüksek', riskLowMessage: 'Eksenler hizalı ve hedef ölçek tam sayı olarak ekrana sığıyor. Yine de filtreleme ile atlas boşluğunu kontrol edin.', riskMediumMessage: 'Hedef kusursuz sığmıyor. Eksen farkını ve vurgulanan ölçekleri inceleyin.', riskHighMessage: 'Bu ölçek düzensiz örnekleme yaratabilir. Tam sayı çarpanı seçin ve boyutları kontrol edin.', alignmentLabel: 'Örnekleme notu', tableTitle: 'Erişilebilir ölçek kaydı', tableScale: 'Ölçek', tableWidth: 'Çizilen genişlik', tableHeight: 'Çizilen yükseklik', tableFits: 'Ekrana sığar', modelNote: 'PPU, her eksende çizilen sprite piksellerinin birim cinsinden sprite boyutuna bölünmesiyle hesaplanır. Bleeding riski sezgiseldir; doku incelemesi veya motor garantisi değildir.', privacyDisclosure: 'Dosya bu tarayıcıda işlenir. Sprite, proje dosyası ve telemetri gönderilmez.', statusReady: 'Önizleme güncellendi', unitPixels: 'px', unitUnits: 'birim',
  },
  seo: [
    { type: 'title', level: 2, text: 'Sprite boyutunu ölçek kararına dönüştürün' }, { type: 'paragraph', html: 'Bir spriteın bitmap boyutu ve oyun dünyasında kapladığı alan vardır. PPU bu iki ölçüyü bağlar. Önizleme, soyut bir sayının yerine görsel sonucu gösterir.' }, { type: 'paragraph', html: 'Gerçek bir görsel yükleyerek yerel boyutlarını kullanın. Araç her ekseni seçilen ölçekle çarpar ve belirtilen çözünürlükte görünen dünya alanını hesaplar.' }, { type: 'title', level: 2, text: 'Önizlemede neye bakmalı' }, { type: 'list', items: ['Footprinti referans ekranıyla karşılaştırın.', 'Eşit pikseller için önce tam sayı ölçeklerini deneyin.', 'İstenmeyen esnemeyi bulmak için iki PPU değerini kullanın.', 'Bleeding uyarısını motor testi için bir işaret sayın.'] }, { type: 'title', level: 2, text: 'Tam sayı ölçekleri neden daha temizdir' }, { type: 'paragraph', html: '3x ölçekte her kaynak pikseli üç ekran pikseli kaplar. 2,5x ölçekte çizici farklı genişlikler dağıtmak zorunda kalır. Nearest renkleri karıştırmaz ama piksel konumları arasındaki kamerayı düzeltemez.' }, { type: 'table', headers: ['Sinyal', 'Anlamı', 'Sonraki karar'], rows: [['Eşit PPU', 'İki eksen aynı yoğunluğa sahip.', 'Tile ve proje ızgarasıyla karşılaştırın.'], ['Kesirli ölçek', 'Footprint tam sayı kullanmıyor.', 'En yakın tam sayı ölçeğini deneyin.'], ['Sığmıyor', 'Sprite ekranı aşıyor.', 'Ölçeği küçültün veya çözünürlüğü artırın.']] }, { type: 'title', level: 2, text: 'Bleeding ile boyutu ayırın' }, { type: 'paragraph', html: 'Pixel bleeding çoğunlukla atlas komşu texellerinden, kenar filtresinden veya hizasız kamera koordinatlarından gelir. Bulanıklıkta filtreyi, dikişlerde ise boşluk ve sınırları da kontrol edin.' }, { type: 'title', level: 2, text: 'Bob spriteıyla akışı öğrenin' }, { type: 'paragraph', html: 'Pembe fiyonklu Bob örneği başlangıçta görünür. Çözünürlük ve ölçeği değiştirerek karakterin ne zaman sığmadığını veya piksellerin eşitliğini kaybettiğini görün.' }, { type: 'title', level: 2, text: 'Araç neyi doğrular ve neyi doğrulamaz' }, { type: 'paragraph', html: 'Araç boyutları ve footprintleri kontrollü bir görünümde karşılaştırır. Motor projesi açmaz, atlas incelemez, cihaz ölçmez ve pixel perfect hareketi garanti etmez.' }, { type: 'title', level: 2, text: 'Ölçek seçmek için kısa akış' }, { type: 'paragraph', html: 'Spriteı yükleyin, çözünürlüğü seçin, 1x ile 4x arasını deneyin ve boşluk bırakan en büyük tam sayı ölçeğini seçin. Gerçek oyun çözünürlüklerinde tekrarlayın.' }, { type: 'tip', title: 'Son kontrol motorda yapılır', html: 'Önizlemeyi seçimi daraltmak için kullanın. Ardından nearest filtreyi, atlas boşluğunu ve kamera hizasını kontrol edin; birkaç çözünürlükte test yapın.' },
  ],
  faqTitle: 'Sprite ölçekleme soruları', faq, bibliographyTitle: 'Pixel art kaynakları', bibliography: bibliographyEntries, howTo, schemas: [softwareApplication, faqPage, howToSchema],
};
