export interface ReactionTesterUI {
  title: string;
  subtitle: string;
  startBtn: string;
  goTitle: string;
  goSubtitle: string;
  earlyTitle: string;
  earlySubtitle: string;
  earlyRetry: string;
  promptNext: string;
  promptFinal: string;
  avgLabel: string;
  copyBtn: string;
  tweetBtn: string;
  retryBtn: string;
  inputMouse: string;
  inputTouch: string;
  inputSpace: string;
  historyTitle: string;
  historyBest: string;
  historyWorst: string;
  historyEmpty: string;
  copySuccess: string;
  shareText: string;
  rankCiberatleta: string;
  rankTigre: string;
  rankHumano: string;
  rankTortuga: string;
  rankDormido: string;
  f150: string;
  f180: string;
  f210: string;
  f250: string;
  f300: string;
  f400: string;
  f600: string;
  fSlow: string;
  wp0t: string; wp0s: string;
  wp1t: string; wp1s: string;
  wp2t: string; wp2s: string;
  wp3t: string; wp3s: string;
  wp4t: string; wp4s: string;
}
