export { steamCapsuleGenerator } from './tool/steamCapsuleGenerator/entry';
export type { SteamCapsuleGeneratorUI, SteamCapsuleGeneratorLocaleContent } from './tool/steamCapsuleGenerator/entry';
export { itchioGameTester } from './tool/itchioGameTester/entry';
export type { ItchioGameTesterUI, ItchioGameTesterLocaleContent } from './tool/itchioGameTester/entry';
export { spriteSheetPacker } from './tool/spriteSheetPacker/entry';
export type { SpriteSheetPackerUI, SpriteSheetPackerLocaleContent } from './tool/spriteSheetPacker/entry';
export { fixerEditor } from './tool/fixerEditor/entry';
export type { FixerEditorUI, FixerEditorLocaleContent } from './tool/fixerEditor/entry';
export { audioLoopPointFinder } from './tool/audioLoopPointFinder/entry';
export type { AudioLoopPointFinderUI, AudioLoopPointFinderLocaleContent } from './tool/audioLoopPointFinder/entry';
export { saveFileEditor } from './tool/saveFileEditor/entry';
export type { SaveFileEditorUI, SaveFileEditorLocaleContent } from './tool/saveFileEditor/entry';
export { localizationSanitizer } from './tool/localizationSanitizer/entry';
export type { LocalizationSanitizerUI, LocalizationSanitizerLocaleContent } from './tool/localizationSanitizer/entry';
export { steamBbcodeTranslator } from './tool/steamBbcodeTranslator/entry';
export type { SteamBbcodeTranslatorUI, SteamBbcodeTranslatorLocaleContent } from './tool/steamBbcodeTranslator/entry';
export { retroSfxGenerator } from './tool/retroSfxGenerator/entry';
export type { RetroSfxGeneratorUI, RetroSfxGeneratorLocaleContent } from './tool/retroSfxGenerator/entry';
export { pixelArtPaletteSwapper } from './tool/pixelArtPaletteSwapper/entry';
export type { PixelArtPaletteSwapperUI, PixelArtPaletteSwapperLocaleContent } from './tool/pixelArtPaletteSwapper/entry';
export { hitboxHurtboxAnimator } from './tool/hitboxHurtboxAnimator/entry';
export type { HitboxHurtboxAnimatorUI, HitboxHurtboxAnimatorLocaleContent } from './tool/hitboxHurtboxAnimator/entry';
export { damageFormulaLab } from './tool/damageFormulaLab/entry';
export type { DamageFormulaLabUI, DamageFormulaLabLocaleContent } from './tool/damageFormulaLab/entry';
export { gameDeltaTimeFixedTimestepLab } from './tool/gameDeltaTimeFixedTimestepLab/entry';
export type { GameDeltaTimeFixedTimestepLabUI, GameDeltaTimeFixedTimestepLabLocaleContent } from './tool/gameDeltaTimeFixedTimestepLab/entry';
export { gamePixelPerUnitPlanner } from './tool/gamePixelPerUnitPlanner/entry';
export type { GamePixelPerUnitPlannerUI, GamePixelPerUnitPlannerLocaleContent } from './tool/gamePixelPerUnitPlanner/entry';
export { isometricTileMapEditor } from './tool/isometricTileMapEditor/entry';
export type { IsometricTileMapEditorUI, IsometricTileMapEditorLocaleContent } from './tool/isometricTileMapEditor/entry';
export { gamesCategory } from './category';

import { isometricTileMapEditor } from './tool/isometricTileMapEditor/entry';

import { steamCapsuleGenerator } from './tool/steamCapsuleGenerator/entry';
import { itchioGameTester } from './tool/itchioGameTester/entry';
import { spriteSheetPacker } from './tool/spriteSheetPacker/entry';
import { audioLoopPointFinder } from './tool/audioLoopPointFinder/entry';
import { saveFileEditor } from './tool/saveFileEditor/entry';
import { localizationSanitizer } from './tool/localizationSanitizer/entry';
import { steamBbcodeTranslator } from './tool/steamBbcodeTranslator/entry';
import { retroSfxGenerator } from './tool/retroSfxGenerator/entry';
import { pixelArtPaletteSwapper } from './tool/pixelArtPaletteSwapper/entry';
import { gameUiAccessibilityTester } from './tool/gameUIAccessibilityTester/entry';
import { hitboxHurtboxAnimator } from './tool/hitboxHurtboxAnimator/entry';
import { damageFormulaLab } from './tool/damageFormulaLab/entry';
import { gameDeltaTimeFixedTimestepLab } from './tool/gameDeltaTimeFixedTimestepLab/entry';
import { gamePixelPerUnitPlanner } from './tool/gamePixelPerUnitPlanner/entry';
import { fixerEditor } from './tool/fixerEditor/entry';

export const ALL_ENTRIES = [steamCapsuleGenerator, itchioGameTester, spriteSheetPacker, audioLoopPointFinder, saveFileEditor, localizationSanitizer, steamBbcodeTranslator, retroSfxGenerator, pixelArtPaletteSwapper, gameUiAccessibilityTester, hitboxHurtboxAnimator, damageFormulaLab, gameDeltaTimeFixedTimestepLab, gamePixelPerUnitPlanner, fixerEditor, isometricTileMapEditor];
